(function(){
'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))},sleep=function(n){return new Promise(function(r){setTimeout(r,n)})};
var intro=$('#intro'),pre=$('#pre'),premsg=$('#premsg'),hack=$('#hack'),final=$('#final'),term=$('#term'),panel=$('#panel'),pt=$('#pt'),px=$('#px'),bar=$('#bar'),profile=$('#profile'),ids=$('#ids'),big=$('#big'),b1=$('#b1'),b2=$('#b2'),b3=$('#b3'),modal=$('#modal'),mtag=$('#mtag'),mtitle=$('#mtitle'),msub=$('#msub'),mbody=$('#mbody'),mreply=$('#mreply'),reveal=$('#reveal'),flash=$('#flash'),rain=$('#rain'),stage=$('#stage');
var r=rain.getContext('2d'),c=stage.getContext('2d'),W=0,H=0,D=1,drops=[],bits=[],key=[],burst=[],cracks=[],running=false,stageRunning=false,last=0,heartBuild=0,keyBuild=0,keyShift=0,keyRot=0,split=0,unlockGlow=0;
function makeIntroStars(){var wrap=$('#stars');if(!wrap)return;for(var i=0;i<34;i++){var s=document.createElement('i');s.className='spark';s.style.left=(Math.random()*100)+'%';s.style.top=(Math.random()*100)+'%';s.style.setProperty('--d',(2.5+Math.random()*5)+'s');s.style.setProperty('--o',(.2+Math.random()*.55));s.style.setProperty('--x',((Math.random()-.5)*50)+'px');s.style.setProperty('--y',((Math.random()-.5)*60)+'px');wrap.appendChild(s)}}
function show(el){el.classList.add('visible')}function hide(el){el.classList.remove('visible')}function kick(cls){hack.classList.remove(cls);void hack.offsetWidth;hack.classList.add(cls);setTimeout(function(){hack.classList.remove(cls)},700)}function flare(){flash.classList.remove('fire');void flash.offsetWidth;flash.classList.add('fire')}
function size(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);[rain,stage].forEach(function(x){x.width=W*D;x.height=H*D;x.style.width=W+'px';x.style.height=H+'px'});r.setTransform(D,0,0,D,0,0);c.setTransform(D,0,0,D,0,0);drops=Array(Math.ceil(W/12)).fill(0).map(function(){return-Math.random()*100})}
function matrix(){if(!running)return;r.fillStyle='rgba(0,0,0,.075)';r.fillRect(0,0,W,H);r.font='11px monospace';for(var i=0;i<drops.length;i++){var y=drops[i];r.fillStyle=Math.random()>.97?'#effff3':'#25ff73';r.fillText(Math.random()>.5?'1':'0',i*12,y*12);drops[i]+=.75+Math.random()*.65;if(y*12>H&&Math.random()>.97)drops[i]=-20}requestAnimationFrame(matrix)}
function heart(t){return{x:16*Math.pow(Math.sin(t),3),y:-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))}}function heartScale(){return Math.min(W,H)*.0174}function heartCenter(){return{x:W/2,y:H*.585}}
function makeHeart(){var a=[],s=heartScale(),hc=heartCenter(),idx=0;for(var q=.08;q<=1;q+=.052){for(var t=0;t<6.28;t+=.105){var p=heart(t),ang=Math.random()*Math.PI*2,rad=Math.max(W,H)*(.25+Math.random()*.5);a.push({x:hc.x+Math.cos(ang)*rad,y:hc.y+Math.sin(ang)*rad,tx:hc.x+p.x*s*q,ty:hc.y+p.y*s*q,vx:0,vy:0,ch:Math.random()>.5?'1':'0',side:p.x<0?-1:1,ring:q,birth:idx++/900+Math.random()*.2})}}return a}
function makeKey(){var a=[],u=Math.min(W,H)*.0115,kx=W*.12,ky=H*.585,idx=0,z,x,y;for(z=0;z<6.28;z+=.11)a.push({x:kx+(Math.random()-.5)*W*.45,y:ky+(Math.random()-.5)*H*.5,tx:kx+Math.cos(z)*u*3.9,ty:ky+Math.sin(z)*u*3.9,vx:0,vy:0,ch:Math.random()>.5?'1':'0',birth:idx++/180});for(x=0;x<u*16;x+=u*.36)a.push({x:kx+(Math.random()-.5)*W*.45,y:ky+(Math.random()-.5)*H*.5,tx:kx+u*3.8+x,ty:ky,vx:0,vy:0,ch:Math.random()>.5?'1':'0',birth:idx++/180});for(y=0;y<u*2.4;y+=u*.36)a.push({x:kx+(Math.random()-.5)*W*.45,y:ky+(Math.random()-.5)*H*.5,tx:kx+u*18,ty:ky+y,vx:0,vy:0,ch:Math.random()>.5?'1':'0',birth:idx++/180});return a}
function move(a,k){for(var i=0;i<a.length;i++){var p=a[i];p.vx+=(p.tx-p.x)*k;p.vy+=(p.ty-p.y)*k;p.vx*=.80;p.vy*=.80;p.x+=p.vx;p.y+=p.vy}}
function pathHeart(ctx,scaleFactor,dx){var hc=heartCenter(),s=heartScale()*scaleFactor;ctx.beginPath();for(var t=0;t<=6.32;t+=.025){var p=heart(t),x=hc.x+p.x*s+(p.x<0?-dx:dx),y=hc.y+p.y*s;t===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.closePath()}
function drawEnergy(ts){if(!bits.length)return;var hc=heartCenter(),base=Math.min(W,H)*.21;for(var i=0;i<3;i++){var rr=base+i*16+Math.sin(ts*.0015+i)*6;c.save();c.strokeStyle='rgba(95,255,157,'+(0.16-i*.035)+')';c.lineWidth=1;c.setLineDash([4+i*3,8+i*2]);c.lineDashOffset=-(ts*.02*(i+1));c.shadowColor='#4cff91';c.shadowBlur=10;c.beginPath();c.ellipse(hc.x,hc.y,rr,rr*.78,ts*.00015*(i%2?1:-1),0,Math.PI*2);c.stroke();c.restore()}}
function drawHeart(ts){if(!bits.length)return;var hc=heartCenter(),pulse=1+Math.sin(ts*.006)*.018*(heartBuild>.9?1:.35);c.save();c.translate(hc.x,hc.y);c.scale(pulse,pulse);c.translate(-hc.x,-hc.y);c.font='11px monospace';c.textAlign='center';for(var i=0;i<bits.length;i++){var p=bits[i];if(p.birth>heartBuild)continue;c.globalAlpha=Math.min(1,(heartBuild-p.birth)*6);c.fillStyle=split>0?'#ff83aa':p.ring>.83?'#e8fff0':'#65ff9e';c.shadowColor=c.fillStyle;c.shadowBlur=p.ring>.83?16:7;c.fillText(p.ch,p.x+p.side*split,p.y)}c.globalAlpha=1;if(heartBuild>.65){c.strokeStyle='rgba(183,255,209,'+Math.min(.7,(heartBuild-.65)*2)+')';c.lineWidth=1.6;c.shadowColor='#66ff9e';c.shadowBlur=16;pathHeart(c,1,split);c.stroke()}if(heartBuild>.88&&split<3){for(var ring=0;ring<3;ring++){var rr=17+ring*7+Math.sin(ts*.004+ring)*2;c.strokeStyle='rgba(183,255,209,'+(.65-ring*.15)+')';c.lineWidth=1;c.shadowColor='#6dff9f';c.shadowBlur=12;c.beginPath();c.arc(hc.x,hc.y,rr,0,Math.PI*2);c.stroke()}c.fillStyle='#00170a';c.beginPath();c.arc(hc.x,hc.y,13,0,Math.PI*2);c.fill();c.fillStyle='#cffff0';c.font='14px monospace';c.fillText('⌁',hc.x,hc.y+5)}c.restore()}
function drawKey(ts){if(!key.length)return;var kx=W*.12,ky=H*.585,cos=Math.cos(keyRot),sin=Math.sin(keyRot);c.save();c.font='11px monospace';c.textAlign='center';for(var i=0;i<key.length;i++){var p=key[i];if(p.birth>keyBuild)continue;var rx=kx+(p.x-kx)*cos-(p.y-ky)*sin+keyShift,ry=ky+(p.x-kx)*sin+(p.y-ky)*cos;c.globalAlpha=Math.min(1,(keyBuild-p.birth)*8);c.fillStyle='#effff4';c.shadowColor='#b5ffca';c.shadowBlur=12+Math.sin(ts*.006+i)*2;c.fillText(p.ch,rx,ry)}c.globalAlpha=1;c.restore()}
function makeCracks(){var hc=heartCenter();cracks=[];for(var b=0;b<8;b++){var pts=[{x:hc.x,y:hc.y}],x=hc.x,y=hc.y,dir=(b/8)*Math.PI*2+Math.random()*.35;for(var i=0;i<6;i++){dir+=(Math.random()-.5)*.7;x+=Math.cos(dir)*(13+Math.random()*17);y+=Math.sin(dir)*(13+Math.random()*17);pts.push({x:x,y:y})}cracks.push(pts)}}
function drawCracks(){if(!cracks.length||unlockGlow<=0)return;c.save();c.lineWidth=1.3;c.strokeStyle='rgba(255,210,226,'+Math.min(1,unlockGlow)+')';c.shadowColor='#ff8fb2';c.shadowBlur=18;c.lineCap='round';for(var i=0;i<cracks.length;i++){var arr=cracks[i];c.beginPath();for(var j=0;j<arr.length;j++){j?c.lineTo(arr[j].x,arr[j].y):c.moveTo(arr[j].x,arr[j].y)}c.stroke()}c.restore()}
function drawBurst(dt){c.font='10px monospace';for(var i=burst.length-1;i>=0;i--){var z=burst[i];z.x+=z.vx*dt*.06;z.y+=z.vy*dt*.06;z.vx*=.985;z.vy*=.985;z.a*=Math.pow(.96,dt/16.7);c.globalAlpha=z.a;c.fillStyle=Math.random()>.65?'#fff':'#ff91b3';c.shadowColor='#ff81aa';c.shadowBlur=8;c.fillText(z.ch,z.x,z.y);if(z.a<.03)burst.splice(i,1)}c.globalAlpha=1}
function explode(){var hc=heartCenter();for(var i=0;i<340;i++){var a=Math.random()*Math.PI*2,s=1.5+Math.random()*7;burst.push({x:hc.x,y:hc.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,a:1,ch:Math.random()>.5?'1':'0'})}}
function draw(ts){if(!stageRunning)return;var dt=Math.min(34,ts-(last||ts));last=ts;c.clearRect(0,0,W,H);move(bits,.044);move(key,.052);drawEnergy(ts);drawHeart(ts);drawKey(ts);drawCracks();drawBurst(dt);requestAnimationFrame(draw)}
function easeOut(p){return 1-Math.pow(1-p,3)}function easeInOut(p){return p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2}function animateProp(setter,from,to,dur,ease){var start=performance.now();return new Promise(function(resolve){function f(now){var p=Math.min(1,(now-start)/dur),e=ease?ease(p):p;setter(from+(to-from)*e);p<1?requestAnimationFrame(f):resolve()}requestAnimationFrame(f)})}
async function line(s,d){term.textContent+=s+'\n';term.scrollTop=term.scrollHeight;await sleep(d||1000)}function state(a,b,p,d){pt.textContent=a;px.textContent=b;bar.style.width=p+'%';panel.classList.toggle('danger',!!d)}
async function alertBig(a,b,d,ok,ms){b1.textContent=a;b2.textContent=b;b3.textContent=d;big.className='overlay '+(ok?'ok':'');show(big);kick(ok?'impact':'chromatic');await sleep(ms||2400);hide(big);await sleep(500)}async function showProfile(){show(profile);await sleep(4200);hide(profile);await sleep(650)}
function setModal(tag,title,sub,html){mtag.textContent=tag;mtitle.textContent=title;msub.textContent=sub||'';mbody.innerHTML=html||'';mreply.innerHTML='';show(modal)}function closeModal(){hide(modal)}function norm(v){return(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function textQuestion(tag,title,hint,answers,bad,mode){return new Promise(function(resolve){setModal(tag,title,hint,'<div class="qrow"><input id="mi" autocomplete="off" spellcheck="false"><button id="mv">VALIDER</button></div>');var input=$('#mi'),btn=$('#mv'),done=false;input.inputMode=mode==='numeric'?'numeric':'text';input.setAttribute('enterkeyhint','done');setTimeout(function(){try{input.focus()}catch(e){}},250);async function submit(){if(done)return;done=true;var ok=answers.some(function(a){return norm(a)===norm(input.value)});input.disabled=btn.disabled=true;if(ok){mreply.innerHTML='&gt; Réponse correcte.<br>&gt; Vérification validée ✅';state('VÉRIFICATION VALIDÉE','Réponse correcte',parseInt(bar.style.width)||30,false);kick('impact')}else{mreply.innerHTML='&gt; RÉPONSE INCORRECTE.<br>&gt; '+bad;state('ERREUR HUMAINE','Réponse tolérée exceptionnellement',parseInt(bar.style.width)||30,true);kick('chromatic')}await sleep(ok?3200:5200);closeModal();await sleep(650);resolve()}btn.onclick=submit;input.onkeydown=function(e){if(e.key==='Enter')submit()}})}
function askChoice(){return new Promise(function(resolve){setModal('PROTOCOLE INATTENDU','Tu croyais que c’était si simple ?','Souhaites-tu continuer ?','<div class="actions"><button id="yes" class="okbtn">OUI</button><button id="no" class="badbtn">NON</button></div>');var done=false;async function fin(type){if(done)return;done=true;if(type==='yes'){mreply.innerHTML='&gt; Décision enregistrée : <b>OUI</b><br>&gt; Courage détecté. Très bon choix, Aline. 😏';state('DÉCISION ACCEPTÉE','Elle veut connaître la suite...',31,false);kick('impact')}else{mreply.innerHTML='&gt; Décision enregistrée : <b>NON</b><br>&gt; Refus détecté… dommage. Le système a décidé de continuer quand même. 😈';state('REFUS IGNORÉ','Trop tard pour reculer maintenant...',31,true);kick('chromatic')}await sleep(6200);closeModal();await sleep(650);resolve()}$('#yes').onclick=function(){fin('yes')};$('#no').onclick=function(){fin('no')}})}
function visualHeart(){return new Promise(function(resolve){setModal('VÉRIFICATION ANTI-ROBOT','Sélectionne le cœur pour prouver que tu es humaine.','Une erreur serait assez gênante.','<div class="icons"><button class="iconbtn" data-v="star">★</button><button class="iconbtn heartchoice" data-v="heart">♥</button><button class="iconbtn" data-v="moon">☾</button><button class="iconbtn" data-v="bolt">⚡</button><button class="iconbtn" data-v="diamond">◆</button><button class="iconbtn" data-v="sun">☀</button></div>');var done=false;$$('.iconbtn').forEach(function(b){b.onclick=async function(){if(done)return;done=true;if(b.dataset.v==='heart'){mreply.innerHTML='&gt; Cœur reconnu.<br>&gt; Bon signe. Très bon signe même. ❤️';kick('impact')}else{mreply.innerHTML='&gt; ÉCHEC.<br>&gt; Tu viens officiellement d’échouer à reconnaître un cœur. Inquiétant. 😂<br>&gt; Le système te laisse passer quand même.';kick('chromatic')}await sleep(5000);closeModal();await sleep(650);resolve()}})})}
function tempCode(){return new Promise(function(resolve){var code='0420';setModal('DOUBLE AUTHENTIFICATION','Code temporaire généré','Recopie simplement le code affiché ci-dessous.','<div class="code">'+code+'</div><div class="qrow"><input id="ci" inputmode="numeric" autocomplete="off"><button id="cv">VALIDER</button></div>');var done=false,input=$('#ci'),btn=$('#cv');async function go(){if(done)return;done=true;input.disabled=btn.disabled=true;if(norm(input.value)===code){mreply.innerHTML='&gt; Code accepté.<br>&gt; Mémoire immédiate : fonctionnelle. ✅';kick('impact')}else{mreply.innerHTML='&gt; Code incorrect.<br>&gt; Pourtant il était littéralement écrit juste au-dessus. 😭<br>&gt; Bon… autorisation exceptionnelle accordée.';kick('chromatic')}await sleep(5200);closeModal();await sleep(650);resolve()}btn.onclick=go;input.onkeydown=function(e){if(e.key==='Enter')go()}})}
function holdTest(){return new Promise(function(resolve){setModal('TEST DE STABILITÉ','Maintiens le bouton pendant 3 secondes.','Ne relâche pas trop tôt.','<div class="actions"><button id="hold" class="okbtn hold"><div id="hf" class="holdfill"></div><span>MAINTENIR</span></button></div>');var b=$('#hold'),f=$('#hf'),start=0,raf=0,done=false;function cancel(){if(done)return;cancelAnimationFrame(raf);start=0;f.style.width='0';mreply.innerHTML='&gt; Relâché trop tôt.<br>&gt; Le système te donne une nouvelle chance. 😏';kick('chromatic')}function tick(ts){if(!start)start=ts;var p=Math.min(1,(ts-start)/3000);f.style.width=(p*100)+'%';if(p>=1){done=true;mreply.innerHTML='&gt; Patience validée.<br>&gt; Niveau étonnamment élevé. ✅';kick('impact');setTimeout(async function(){closeModal();await sleep(650);resolve()},2800)}else raf=requestAnimationFrame(tick)}function begin(e){if(e&&e.preventDefault)e.preventDefault();if(done)return;start=0;mreply.innerHTML='';raf=requestAnimationFrame(tick)}b.addEventListener('pointerdown',begin);b.addEventListener('pointerup',cancel);b.addEventListener('pointerleave',cancel);b.addEventListener('pointercancel',cancel);b.addEventListener('touchstart',begin,{passive:false});b.addEventListener('touchend',cancel,{passive:false})})}
function folderAuth(){return new Promise(function(resolve){setModal('AUTORISATION SYSTÈME','Accès à une zone privée','Le dossier suivant demande ton autorisation.','<div class="fakepath">/Florent/Cœur/Zone_privée</div><div class="actions"><button id="fa" class="okbtn">AUTORISER</button><button id="fr" class="badbtn">REFUSER</button></div>');var done=false;async function fin(ok){if(done)return;done=true;if(ok){mreply.innerHTML='&gt; Autorisation reçue.<br>&gt; Ouverture du dossier privé…';kick('impact')}else{mreply.innerHTML='&gt; Refus enregistré.<br>&gt; Le propriétaire du cœur a annulé ton refus. 😈<br>&gt; Autorisation forcée.';kick('chromatic')}await sleep(5400);closeModal();await sleep(650);resolve()}$('#fa').onclick=function(){fin(true)};$('#fr').onclick=function(){fin(false)}})}
function finalGate(){return new Promise(function(resolve){setModal('ERREUR 0xLOVE','DERNIÈRE AUTHENTIFICATION REQUISE','Souhaites-tu vraiment savoir ce qu’il y a derrière cette porte ?','<div class="actions lastbuttons"><button id="fy" class="okbtn">OUI</button><button id="fe" class="okbtn">ÉVIDEMMENT</button></div>');var done=false;async function fin(){if(done)return;done=true;mreply.innerHTML='&gt; Autorisation finale accordée.<br>&gt; Attention : contenu hautement sentimental. ❤️';kick('impact');await sleep(5200);closeModal();await sleep(650);resolve()}$('#fy').onclick=fin;$('#fe').onclick=fin})}
async function scanNames(){ids.innerHTML='';show(ids);var list1=['Emma','Léa','Chloé'];for(var i=0;i<list1.length;i++){var d=document.createElement('div');d.className='id';d.innerHTML='<small>IDENTITÉ TESTÉE</small><strong>'+list1[i]+'</strong><small>ACCÈS REFUSÉ · signature invalide</small>';ids.appendChild(d);kick('chromatic');await sleep(1950)}hide(ids);await sleep(750);await askChoice();ids.innerHTML='';show(ids);var list2=['Sarah','Camille'];for(i=0;i<list2.length;i++){d=document.createElement('div');d.className='id';d.innerHTML='<small>NOUVELLE TENTATIVE</small><strong>'+list2[i]+'</strong><small>ACCÈS REFUSÉ · non compatible</small>';ids.appendChild(d);kick('chromatic');await sleep(1950)}var a=document.createElement('div');a.className='id allow';a.innerHTML='<small>CORRESPONDANCE UNIQUE</small><strong>ALINE</strong><small>AUTORISATION ABSOLUE · NIVEAU ∞</small>';ids.appendChild(a);flare();kick('impact');await sleep(3900);hide(ids)}
async function cinematicHeartBuild(){bits=makeHeart();heartBuild=0;state('RECONSTRUCTION DU CŒUR','Assemblage des fragments binaires',70,false);await animateProp(function(v){heartBuild=v},0,1,7200,easeInOut);await sleep(900)}
async function cinematicKey(){key=makeKey();keyBuild=0;state('FORGEAGE DE LA CLÉ','Signature : ALINE',90,false);await animateProp(function(v){keyBuild=v},0,1,4100,easeOut);await sleep(700);var hc=heartCenter(),target=hc.x-W*.12;await animateProp(function(v){keyShift=v},0,target,2900,easeInOut);await sleep(450);await line('> Insertion de la clé...',1200);await animateProp(function(v){keyShift=v},target,target+22,950,easeOut);await line('> Rotation de la clé...',1100);await animateProp(function(v){keyRot=v},0,Math.PI/2,1700,easeInOut);flare();kick('impact');await sleep(500)}
async function cinematicUnlock(){makeCracks();unlockGlow=0;state('OUVERTURE DU CŒUR','Rupture des couches chiffrées',98,false);await animateProp(function(v){unlockGlow=v},0,1,1400,easeOut);flare();await sleep(600);await animateProp(function(v){split=v},0,Math.min(W*.18,95),2600,easeInOut);explode();flare();kick('impact');reveal.classList.add('on');await sleep(5600)}
async function go(){if(running)return;intro.classList.add('off');pre.classList.remove('off');var steps=[['Chargement du message...',2500],['Vérification de l’intégrité...',2200],['Connexion au message sécurisé...',2200],['Anomalie détectée...',2300],['Connexion interrompue.',2000]];for(var i=0;i<steps.length;i++){premsg.textContent=steps[i][0];if(steps[i][0].indexOf('Anomalie')>=0)pre.classList.add('glitch');await sleep(steps[i][1])}pre.classList.add('off');hack.classList.remove('off');size();running=stageRunning=true;matrix();requestAnimationFrame(draw);state('SURVEILLANCE','Analyse du canal...',4,false);await line('> Canal ouvert.',1300);await line('> Lecture des métadonnées régionales...',1450);state('PROFILAGE RÉGIONAL','Localisation approximative détectée',12,false);await line('> Localisation estimée : ROCHE, SUISSE.',1600);await line('> Langue : français (CH).',1450);await showProfile();
await textQuestion('VÉRIFICATION HUMAINE 1/3','Quelle est la capitale de la France ?','Très difficile, attention 😏',['paris'],'Faux ! La réponse était Paris. Bon… on va être gentil pour cette fois-ci. 😌','text');
await visualHeart();state('ALERTE SYSTÈME','Connexion extérieure interceptée',19,true);kick('chromatic');await line('> Session verrouillée.',1500);
await textQuestion('VÉRIFICATION HUMAINE 2/3','4 + 5 = ?','Le système surveille très attentivement cette opération.',['9','neuf'],'Faux. C’était 9. Là, Aline, le système commence sérieusement à s’inquiéter. 😂','numeric');
await tempCode();await line('> Recherche d’une identité autorisée...',1600);await scanNames();await holdTest();await line('> Correspondance unique trouvée : ALINE',1550);await alertBig('IDENTITÉ VALIDÉE','ALINE','Autorisation absolue · niveau ∞',true,3000);state('IDENTITÉ CONFIRMÉE','Aline · accès spécial détecté',42,false);
await folderAuth();await line('> Exploration des zones privées...',1500);await line('> Cible : CŒUR DE FLORENT',1800);await alertBig('ZONE ULTRA-PROTÉGÉE','ACCÈS REFUSÉ','Clé émotionnelle requise',false,2800);state('ACCÈS AU NOYAU','Extraction du cœur',62,false);await line('> Fichier trouvé : coeur_florent.core',1600);await line('> Extraction de 4 096 fragments émotionnels...',1700);await cinematicHeartBuild();await alertBig('CŒUR RECONSTRUIT','VERROU ACTIF','Dernière identité requise',false,2800);
await textQuestion('VÉRIFICATION HUMAINE 3/3','Qui est la seule personne autorisée à ouvrir le cœur de Florent ?','Indice : elle est actuellement devant cet écran. 😈',['aline'],'Faux… la réponse était ALINE. Même le cœur vient de lever les yeux au ciel. 😂 Bon, accès provisoire accordé.','text');
await finalGate();await line('> Analyse de 1 024 clés...',1600);await line('> 1 023 clés rejetées.',1600);await line('> Une clé parfaite détectée.',1800);await alertBig('CLÉ UNIQUE','ALINE','Compatibilité : 100 %',true,3000);await cinematicKey();await line('> Serrure principale désactivée.',1600);await line('> Validation émotionnelle...',1900);bar.style.width='100%';await alertBig('ACCÈS AUTORISÉ','ALINE','Tu es la seule autorisée ❤️',true,3400);await cinematicUnlock();hack.classList.add('off');final.classList.remove('off');running=stageRunning=false}
makeIntroStars();$('#open').onclick=go;$('#again').onclick=function(){location.reload()};setInterval(function(){try{$('#clock').textContent=new Date().toLocaleTimeString('fr-CH')}catch(e){$('#clock').textContent=new Date().toLocaleTimeString()}},1000);addEventListener('resize',function(){if(running)size()});
})();