(function(){
'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))},sleep=function(ms){return new Promise(function(r){setTimeout(r,ms)})};
var intro=$('#intro'),card=$('#introCard'),heart=$('#heroHeart'),open=$('#open'),infection=$('#infection'),assembly=$('#hackAssembly'),hack=$('#hack'),modal=$('#modal'),profile=$('#profile'),ids=$('#ids'),big=$('#big'),reveal=$('#reveal'),final=$('#final'),finalBridge=$('#finalBridge'),soul=$('#soulHeart'),soundToggle=$('#soundToggle'),soundLabel=$('#soundLabel'),mreply=$('#mreply');
var coarse=window.matchMedia&&window.matchMedia('(pointer:coarse)').matches,muted=false,audioCtx=null,heartbeatTimer=0,lastReply='';
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function vibrate(pattern){try{if(navigator.vibrate)navigator.vibrate(pattern)}catch(e){}}
function ensureAudio(){if(muted)return null;try{if(!audioCtx){var AC=window.AudioContext||window.webkitAudioContext;if(AC)audioCtx=new AC()}if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch(e){return null}}
function tone(freq,dur,type,vol,delay){var ac=ensureAudio();if(!ac)return;try{var o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+(delay||0);o.type=type||'sine';o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol||.035,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+dur+.03)}catch(e){}}
function noise(dur,vol){var ac=ensureAudio();if(!ac)return;try{var n=Math.floor(ac.sampleRate*dur),b=ac.createBuffer(1,n,ac.sampleRate),d=b.getChannelData(0);for(var i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);var s=ac.createBufferSource(),g=ac.createGain();s.buffer=b;g.gain.value=vol||.012;s.connect(g);g.connect(ac.destination);s.start()}catch(e){}}
function sound(kind){if(muted)return;if(kind==='tap'){tone(520,.08,'sine',.025)}else if(kind==='ok'){tone(620,.16,'sine',.028);tone(930,.22,'sine',.022,.08)}else if(kind==='bad'){tone(145,.22,'sawtooth',.018);noise(.16,.008)}else if(kind==='hack'){tone(82,.5,'sawtooth',.018);tone(164,.35,'square',.008,.18);noise(.3,.008)}else if(kind==='unlock'){tone(220,.4,'sine',.02);tone(440,.6,'sine',.025,.12);tone(660,.8,'sine',.018,.26)}else if(kind==='heart'){tone(72,.11,'sine',.018);tone(58,.1,'sine',.012,.13)}}
function startHeartbeat(){clearInterval(heartbeatTimer);heartbeatTimer=setInterval(function(){if(!muted&&!intro.classList.contains('off'))sound('heart')},1650)}function stopHeartbeat(){clearInterval(heartbeatTimer)}
function setSoul(mode){if(!soul)return;soul.className='soul-heart '+mode+'-mode'}
function makeStars(id,count){var wrap=$(id);if(!wrap||wrap.children.length)return;for(var i=0;i<count;i++){var s=document.createElement('i');s.className=id==='#finalStars'?'final-star':'spark';s.style.left=(Math.random()*100)+'%';s.style.top=(Math.random()*100)+'%';s.style.setProperty('--d',(2.5+Math.random()*5)+'s');s.style.setProperty('--o',(.18+Math.random()*.6));s.style.setProperty('--x',((Math.random()-.5)*55)+'px');s.style.setProperty('--y',((Math.random()-.5)*65)+'px');wrap.appendChild(s)}}
function parallax(x,y){if(!card||coarse)return;var rx=clamp((.5-y/window.innerHeight)*8,-6,6),ry=clamp((x/window.innerWidth-.5)*10,-7,7);card.style.transform='rotateX('+rx+'deg) rotateY('+ry+'deg) translateZ(0)';if(heart)heart.style.transform='translate3d('+ry*1.7+'px,'+(-rx*1.5)+'px,42px)'}
if(intro){intro.addEventListener('pointermove',function(e){parallax(e.clientX,e.clientY)});intro.addEventListener('pointerleave',function(){if(card)card.style.transform='';if(heart)heart.style.transform=''})}
function pulseAt(x,y){var d=document.createElement('i');d.className='tap-ripple';d.style.left=x+'px';d.style.top=y+'px';document.body.appendChild(d);setTimeout(function(){if(d.parentNode)d.parentNode.removeChild(d)},760)}document.addEventListener('pointerdown',function(e){var b=e.target.closest&&e.target.closest('button');if(b){pulseAt(e.clientX,e.clientY);sound('tap');vibrate(8)}},{passive:true});
/* Bouton principal magnétique sur pointeur précis. */
if(open&&!coarse){open.addEventListener('pointermove',function(e){var r=open.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.18;open.classList.add('magnetic');open.style.transform='translate3d('+x+'px,'+y+'px,34px) scale(1.025)'});open.addEventListener('pointerleave',function(){open.classList.remove('magnetic');open.style.transform=''})}
if(soundToggle){soundToggle.addEventListener('click',function(e){e.stopPropagation();muted=!muted;soundToggle.classList.toggle('muted',muted);soundLabel.textContent=muted?'SON : COUPÉ':'SON : ACTIVÉ';if(!muted){ensureAudio();sound('ok');startHeartbeat()}else stopHeartbeat()})}
/* Le HUD réagit aux fenêtres ouvertes. */
if(window.MutationObserver&&hack){var focusObs=new MutationObserver(function(){var focus=[modal,profile,ids,big].some(function(el){return el&&el.classList.contains('visible')});hack.classList.toggle('hud-focus',focus)});[modal,profile,ids,big].forEach(function(el){if(el)focusObs.observe(el,{attributes:true,attributeFilter:['class']})})}
/* Réactions physiques + son à la validation, déduites du texte déjà produit par app.js. */
if(window.MutationObserver&&mreply){new MutationObserver(function(){var text=mreply.textContent||'';if(!text||text===lastReply)return;lastReply=text;modal.classList.remove('physical-success','physical-error');if(/incorrecte|échec|refus|dommage|trop tôt|forcée/i.test(text)){modal.classList.add('physical-error');sound('bad');vibrate([25,35,25])}else if(/correcte|validée|accepté|reconnu|autorisation|patience|accordée/i.test(text)){modal.classList.add('physical-success');sound('ok');vibrate(18)}setTimeout(function(){modal.classList.remove('physical-success','physical-error')},850)}).observe(mreply,{childList:true,subtree:true,characterData:true})}
/* Lancement V6 : le même cœur se contracte puis contamine l'écran. */
if(open){var legacy=open.onclick;open.onclick=null;open.addEventListener('click',async function(e){e.preventDefault();if(open.dataset.busy)return;open.dataset.busy='1';ensureAudio();sound('heart');startHeartbeat();vibrate([18,35,28]);open.classList.add('arming');if(card)card.classList.add('collapse');setSoul('hack');await sleep(360);if(infection){infection.classList.remove('active');void infection.offsetWidth;infection.classList.add('active')}sound('hack');await sleep(820);stopHeartbeat();if(typeof legacy==='function')legacy.call(open,e);if(assembly){assembly.classList.remove('active');void assembly.offsetWidth;assembly.classList.add('active')}setTimeout(function(){if(infection)infection.classList.remove('active')},2700)},{once:true})}
/* Synchronise le cœur permanent avec les scènes réellement jouées. */
if(window.MutationObserver&&hack){new MutationObserver(function(){if(!hack.classList.contains('off'))setSoul('hack')}).observe(hack,{attributes:true,attributeFilter:['class']})}
if(window.MutationObserver&&reveal){new MutationObserver(function(){if(reveal.classList.contains('on')){setSoul('reveal');sound('unlock');vibrate([30,45,55]);if(finalBridge){finalBridge.classList.remove('active');void finalBridge.offsetWidth;setTimeout(function(){finalBridge.classList.add('active')},3200)}}}).observe(reveal,{attributes:true,attributeFilter:['class']})}
if(window.MutationObserver&&final){new MutationObserver(function(){if(!final.classList.contains('off')){setSoul('final');makeStars('#finalStars',36);if(finalBridge&&!finalBridge.classList.contains('active')){finalBridge.classList.add('active')}sound('ok')}}).observe(final,{attributes:true,attributeFilter:['class']})}
/* Petits sons sur les grands panneaux d'état. */
if(window.MutationObserver&&big){new MutationObserver(function(){if(big.classList.contains('visible')){var txt=(big.textContent||'').toLowerCase();if(/refus|verrou|erreur/.test(txt)){sound('bad');vibrate(22)}else{sound('ok');vibrate(14)}}}).observe(big,{attributes:true,attributeFilter:['class']})}
makeStars('#stars',38);makeStars('#finalStars',36);startHeartbeat();
})();