(function(){
'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))},sleep=function(ms){return new Promise(function(r){setTimeout(r,ms)})};
var intro=$('#intro'),card=$('#introCard'),heart=$('#heroHeart'),open=$('#open'),infection=$('#infection'),assembly=$('#hackAssembly'),hack=$('#hack'),modal=$('#modal'),profile=$('#profile'),ids=$('#ids'),big=$('#big'),reveal=$('#reveal'),final=$('#final'),bridge=$('#finalBridge'),soul=$('#soulHeart'),soundToggle=$('#soundToggle'),soundLabel=$('#soundLabel'),mreply=$('#mreply');
var coarse=window.matchMedia&&window.matchMedia('(pointer:coarse)').matches,muted=false,activated=false,audioCtx=null,heartbeatTimer=0,lastReply='';
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function vib(p){try{if(navigator.vibrate)navigator.vibrate(p)}catch(e){}}
function ensureAudio(){if(muted||!activated)return null;try{if(!audioCtx){var AC=window.AudioContext||window.webkitAudioContext;if(AC)audioCtx=new AC()}if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch(e){return null}}
function tone(f,d,type,v,delay){var ac=ensureAudio();if(!ac)return;try{var o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+(delay||0);o.type=type||'sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v||.03,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+d+.03)}catch(e){}}
function noise(d,v){var ac=ensureAudio();if(!ac)return;try{var n=Math.floor(ac.sampleRate*d),b=ac.createBuffer(1,n,ac.sampleRate),x=b.getChannelData(0);for(var i=0;i<n;i++)x[i]=(Math.random()*2-1)*(1-i/n);var s=ac.createBufferSource(),g=ac.createGain();s.buffer=b;g.gain.value=v||.01;s.connect(g);g.connect(ac.destination);s.start()}catch(e){}}
function sound(k){if(muted||!activated)return;if(k==='tap')tone(520,.08,'sine',.025);if(k==='ok'){tone(620,.16,'sine',.028);tone(930,.22,'sine',.022,.08)}if(k==='bad'){tone(145,.22,'sawtooth',.018);noise(.16,.008)}if(k==='hack'){tone(82,.5,'sawtooth',.018);tone(164,.35,'square',.008,.18);noise(.3,.008)}if(k==='unlock'){tone(220,.4,'sine',.02);tone(440,.6,'sine',.025,.12);tone(660,.8,'sine',.018,.26)}if(k==='heart'){tone(72,.11,'sine',.018);tone(58,.1,'sine',.012,.13)}}
function startHeart(){clearInterval(heartbeatTimer);heartbeatTimer=setInterval(function(){if(activated&&!muted&&!intro.classList.contains('off'))sound('heart')},1650)}function stopHeart(){clearInterval(heartbeatTimer)}function setSoul(m){if(soul)soul.className='soul-heart '+m+'-mode'}
function stars(id,n){var w=$(id);if(!w||w.children.length)return;for(var i=0;i<n;i++){var s=document.createElement('i');s.className=id==='#finalStars'?'final-star':'spark';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.setProperty('--d',2.5+Math.random()*5+'s');s.style.setProperty('--o',.18+Math.random()*.6);s.style.setProperty('--x',(Math.random()-.5)*55+'px');s.style.setProperty('--y',(Math.random()-.5)*65+'px');w.appendChild(s)}}
function parallax(x,y){if(!card||coarse)return;var rx=clamp((.5-y/innerHeight)*8,-6,6),ry=clamp((x/innerWidth-.5)*10,-7,7);card.style.transform='rotateX('+rx+'deg) rotateY('+ry+'deg)';if(heart)heart.style.transform='translate3d('+ry*1.7+'px,'+(-rx*1.5)+'px,42px)'}if(intro){intro.addEventListener('pointermove',function(e){parallax(e.clientX,e.clientY)});intro.addEventListener('pointerleave',function(){if(card)card.style.transform='';if(heart)heart.style.transform=''})}
function ripple(x,y){var d=document.createElement('i');d.className='tap-ripple';d.style.left=x+'px';d.style.top=y+'px';document.body.appendChild(d);setTimeout(function(){if(d.parentNode)d.remove()},760)}
document.addEventListener('pointerdown',function(e){activated=true;var b=e.target.closest&&e.target.closest('button');if(b){ripple(e.clientX,e.clientY);sound('tap');vib(8)}},{passive:true});
if(open&&!coarse){open.addEventListener('pointermove',function(e){var r=open.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.18;open.classList.add('magnetic');open.style.transform='translate3d('+x+'px,'+y+'px,34px) scale(1.025)'});open.addEventListener('pointerleave',function(){open.classList.remove('magnetic');open.style.transform=''})}
if(soundToggle)soundToggle.addEventListener('click',function(e){e.stopPropagation();activated=true;muted=!muted;soundToggle.classList.toggle('muted',muted);soundLabel.textContent=muted?'SON : COUPÉ':'SON : ACTIVÉ';if(!muted){ensureAudio();sound('ok');startHeart()}else stopHeart()});
if(window.MutationObserver&&hack){var fo=new MutationObserver(function(){hack.classList.toggle('hud-focus',[modal,profile,ids,big].some(function(el){return el&&el.classList.contains('visible')}))});[modal,profile,ids,big].forEach(function(el){if(el)fo.observe(el,{attributes:true,attributeFilter:['class']})})}
if(window.MutationObserver&&mreply)new MutationObserver(function(){var t=mreply.textContent||'';if(!t||t===lastReply)return;lastReply=t;modal.classList.remove('physical-success','physical-error');if(/incorrecte|échec|refus|dommage|trop tôt|forcée/i.test(t)){modal.classList.add('physical-error');sound('bad');vib([25,35,25])}else if(/correcte|validée|accepté|reconnu|autorisation|patience|accordée/i.test(t)){modal.classList.add('physical-success');sound('ok');vib(18)}setTimeout(function(){modal.classList.remove('physical-success','physical-error')},850)}).observe(mreply,{childList:true,subtree:true,characterData:true});
if(open){var legacy=open.onclick;open.onclick=null;open.addEventListener('click',async function(e){e.preventDefault();if(open.dataset.busy)return;activated=true;open.dataset.busy='1';ensureAudio();sound('heart');startHeart();vib([18,35,28]);if(card)card.classList.add('collapse');setSoul('hack');await sleep(360);if(infection){infection.classList.remove('active');void infection.offsetWidth;infection.classList.add('active')}sound('hack');await sleep(820);stopHeart();if(typeof legacy==='function')legacy.call(open,e);if(assembly){assembly.classList.remove('active');void assembly.offsetWidth;assembly.classList.add('active')}setTimeout(function(){if(infection)infection.classList.remove('active')},2700)},{once:true})}
if(window.MutationObserver&&hack)new MutationObserver(function(){if(!hack.classList.contains('off'))setSoul('hack')}).observe(hack,{attributes:true,attributeFilter:['class']});
if(window.MutationObserver&&reveal)new MutationObserver(function(){if(reveal.classList.contains('on')){setSoul('reveal');sound('unlock');vib([30,45,55]);if(bridge){bridge.classList.remove('active');void bridge.offsetWidth;setTimeout(function(){bridge.classList.add('active')},3200)}}}).observe(reveal,{attributes:true,attributeFilter:['class']});
if(window.MutationObserver&&final)new MutationObserver(function(){if(!final.classList.contains('off')){setSoul('final');stars('#finalStars',36);if(bridge&&!bridge.classList.contains('active'))bridge.classList.add('active');sound('ok')}}).observe(final,{attributes:true,attributeFilter:['class']});
if(window.MutationObserver&&big)new MutationObserver(function(){if(big.classList.contains('visible')){var t=(big.textContent||'').toLowerCase();if(/refus|verrou|erreur/.test(t)){sound('bad');vib(22)}else{sound('ok');vib(14)}}}).observe(big,{attributes:true,attributeFilter:['class']});
stars('#stars',38);stars('#finalStars',36);
})();