(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const scene=$('#scene'),hud=$('#hud'),fill=$('#progressFill'),progressText=$('#progressText'),guide=$('#guide'),guideText=$('#guideText'),transition=$('#transition'),transitionTitle=$('#transitionTitle'),toastBox=$('#toast'),flash=$('#flash'),soundBtn=$('#soundBtn'),qualityBtn=$('#qualityBtn');
const reduced=window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const state={step:0,sound:true,quality:'auto',leadRound:0,leadWins:0,boss:25,bossHits:0};
let audio=null,toastTimer=null,leadTimer=null,leadOpen=false;

function theme(name=''){document.body.className=document.body.className.replace(/theme-[\w-]+/g,'').trim();if(name)document.body.classList.add('theme-'+name)}
function progress(n){state.step=n;fill.style.width=((n/4)*100)+'%';progressText.textContent=`${n} / 4`;hud.classList.toggle('hidden',n===0)}
function render(html,t=''){theme(t);scene.className='scene';void scene.offsetWidth;scene.innerHTML=html;window.scrollTo({top:0,left:0,behavior:'auto'})}
function ensureAudio(){if(!state.sound)return null;try{const AC=window.AudioContext||window.webkitAudioContext;if(!audio&&AC)audio=new AC();if(audio&&audio.state==='suspended')audio.resume();return audio}catch(_){return null}}
function tone(f=420,d=.13,v=.008,type='sine',delay=0){const ac=ensureAudio();if(!ac)return;try{const o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+d+.03)}catch(_){}}
function sfx(k){if(k==='ok'){tone(520,.13,.009);tone(780,.18,.006,'sine',.07)}else if(k==='bad'){tone(145,.18,.007,'triangle');tone(105,.22,.005,'sine',.04)}else if(k==='hit'){tone(95,.22,.009,'triangle');tone(190,.14,.005,'sine',.04)}else{tone(310,.16,.005);tone(465,.2,.004,'sine',.08)}}
function haptic(p){try{navigator.vibrate&&navigator.vibrate(p)}catch(_){}}
function burst(x,y,n=8){if(reduced||document.documentElement.classList.contains('quality-low'))return;for(let i=0;i<n;i++){const p=document.createElement('i');p.className='burst';p.style.left=x+'px';p.style.top=y+'px';const a=Math.random()*Math.PI*2,d=30+Math.random()*76;p.style.setProperty('--x',Math.cos(a)*d+'px');p.style.setProperty('--y',Math.sin(a)*d+'px');document.body.appendChild(p);setTimeout(()=>p.remove(),760)}}
function sparkle(){flash.classList.remove('on');void flash.offsetWidth;flash.classList.add('on');sfx('ok');haptic(18);burst(innerWidth/2,innerHeight/2,18)}
function toast(t){clearTimeout(toastTimer);toastBox.textContent=t;toastBox.classList.add('on');toastTimer=setTimeout(()=>toastBox.classList.remove('on'),2300)}
async function say(t,ms=2400){guideText.textContent=t;guide.classList.remove('hidden');sfx('soft');await sleep(ms);guide.classList.add('hidden')}
async function travel(title,fn){if(reduced){fn();return}transitionTitle.textContent=title;transition.classList.add('on');await sleep(430);fn();await sleep(260);transition.classList.remove('on')}
function button(label,id,cls='primary'){return `<button id="${id}" class="${cls}" type="button">${label}</button>`}
function tech(name,desc){return `<div class="tech"><small>LE VRAI NOM, MAINTENANT QUE TU AS COMPRIS</small><b>${name} ✓</b><div style="margin-top:5px;color:#96a5b8;font-size:12px;line-height:1.45">${desc}</div></div>`}

document.addEventListener('pointerdown',e=>{const b=e.target.closest&&e.target.closest('button');if(!b)return;haptic(5);const r=b.getBoundingClientRect(),rip=document.createElement('i');rip.className='ripple';rip.style.left=(e.clientX-r.left)+'px';rip.style.top=(e.clientY-r.top)+'px';b.appendChild(rip);setTimeout(()=>rip.remove(),620);burst(e.clientX,e.clientY,5)},{passive:true});
soundBtn.onclick=()=>{state.sound=!state.sound;soundBtn.textContent=state.sound?'SON':'MUET';if(state.sound){ensureAudio();sfx('ok')}};
qualityBtn.onclick=()=>{state.quality=state.quality==='auto'?'low':state.quality==='low'?'max':'auto';qualityBtn.textContent=state.quality==='low'?'FLUIDE':state.quality==='max'?'MAX':'AUTO';document.documentElement.classList.toggle('quality-low',state.quality==='low');document.documentElement.classList.toggle('quality-max',state.quality==='max');resizeFx()};

/* Canvas V6 : décor vivant et contextuel */
const canvas=$('#fx'),ctx=canvas.getContext('2d',{alpha:true});let W=0,H=0,D=1,motes=[],last=performance.now();
const palettes={home:[[103,239,255],[144,118,255],[255,133,185]],brief:[[102,237,255],[144,120,255],[255,210,118]],copy:[[102,255,211],[97,225,255],[151,132,255]],lead:[[94,230,255],[117,119,255],[255,116,185]],cross:[[255,215,108],[93,229,255],[255,127,159]],boss:[[255,95,128],[255,174,73],[193,99,255]],aline:[[255,156,190],[255,220,230],[211,163,255]]};
function currentPalette(){const c=document.body.className;for(const k of Object.keys(palettes))if(c.includes('theme-'+k))return palettes[k];return palettes.home}
function makeMote(){return{x:Math.random()*W,y:Math.random()*H,r:.4+Math.random()*1.4,v:.04+Math.random()*.16,a:.08+Math.random()*.28,c:Math.floor(Math.random()*3),phase:Math.random()*6.28}}
function resizeFx(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,document.documentElement.classList.contains('quality-low')?1:1.5);canvas.width=Math.max(1,Math.floor(W*D));canvas.height=Math.max(1,Math.floor(H*D));canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);const n=reduced?0:(document.documentElement.classList.contains('quality-low')?26:Math.min(80,Math.max(42,Math.floor(W/11))));motes=Array.from({length:n},makeMote)}
function rgba(c,a){return`rgba(${c[0]},${c[1]},${c[2]},${a})`}
function fx(now){const dt=Math.min(35,now-last||16);last=now;ctx.clearRect(0,0,W,H);const pal=currentPalette();ctx.globalCompositeOperation='lighter';for(const p of motes){p.y-=p.v*dt*.06;p.x+=Math.sin(now*.00035+p.phase)*p.v*.4;if(p.y<-10){p.y=H+10;p.x=Math.random()*W}if(p.x<-10)p.x=W+10;if(p.x>W+10)p.x=-10;const c=pal[p.c];ctx.fillStyle=rgba(c,p.a);ctx.shadowColor=rgba(c,.45);ctx.shadowBlur=8;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}const cls=document.body.className;if(!reduced&&!document.documentElement.classList.contains('quality-low')){if(cls.includes('theme-lead')){const y=H*.49,g=ctx.createLinearGradient(W*.18,y,W*.82,y);g.addColorStop(0,rgba(pal[0],0));g.addColorStop(.5,rgba(pal[1],.14));g.addColorStop(1,rgba(pal[2],0));ctx.strokeStyle=g;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(W*.18,y);ctx.lineTo(W*.82,y);ctx.stroke()}else if(cls.includes('theme-boss')){ctx.strokeStyle=rgba(pal[0],.08);ctx.lineWidth=1;ctx.beginPath();ctx.arc(W*.5,H*.48,Math.min(W,H)*.24,now*.0002,now*.0002+4.4);ctx.stroke()}else if(cls.includes('theme-aline')){for(let i=0;i<30;i++){const a=i/30*Math.PI*2,x=16*Math.pow(Math.sin(a),3),y=-(13*Math.cos(a)-5*Math.cos(2*a)-2*Math.cos(3*a)-Math.cos(4*a));ctx.fillStyle=rgba(pal[i%3],.08);ctx.beginPath();ctx.arc(W*.5+x*Math.min(W,H)*.008,H*.43+y*Math.min(W,H)*.008,1.3,0,6.28);ctx.fill()}}}ctx.shadowBlur=0;ctx.globalCompositeOperation='source-over';requestAnimationFrame(fx)}
addEventListener('resize',resizeFx,{passive:true});resizeFx();requestAnimationFrame(fx);

function home(){progress(0);render(`<div class="wrap hero"><div class="hero-copy"><div class="eyebrow"><i></i>EXPÉRIENCE PRIVÉE · ALINE</div><h1><span>Entre dans le monde de Flo.</span><em>ALINE PROTOCOL · HYPERSMART LAB</em></h1><p>Tu n’as rien à apprendre avant de commencer. <strong>Regarde, joue, puis seulement après je te dirai ce que tu viens de comprendre.</strong></p><div class="hero-actions">${button('OUVRIR LE LABORATOIRE','enter')}<span class="micro">3 expériences · 1 boss · zéro cours</span></div></div><div class="portal-sculpture" aria-hidden="true"><div class="portal-orbit"><i class="portal-node n1"></i><i class="portal-node n2"></i><i class="portal-node n3"></i><div class="aline-core"><b>A</b></div><div class="portal-caption"><small>ACCÈS AUTORISÉ</small><b>Invitée reconnue : Aline</b></div></div></div></div>`,'home');$('#enter').onclick=async()=>{ensureAudio();sparkle();await travel('BIENVENUE',briefing);say('Promis : aucun vocabulaire compliqué. Regarde juste ce qui se passe. 😌',2600)}}

function briefing(){progress(0);render(`<div class="wrap level"><div class="level-top"><div><div class="level-index">MISSION</div><h2>Trois choses à découvrir.</h2></div><div class="pill">TU PEUX TE TROMPER</div></div><p class="hint">Tu vas répondre à trois questions très simples : qui semble vraiment bon, qui bouge en premier, et si une bonne affaire est vraiment bonne.</p><div class="stage" style="min-height:390px;display:grid;place-items:center"><div style="width:min(760px,88%);display:grid;grid-template-columns:repeat(3,1fr);gap:18px;text-align:center"><div><div style="font-size:54px">◎</div><b>Qui est vraiment bon ?</b></div><div><div style="font-size:54px">⚡</div><b>Qui bouge d’abord ?</b></div><div><div style="font-size:54px">◇</div><b>Bonne affaire ou piège ?</b></div></div></div><div class="actions">${button('COMMENCER','start')}</div></div>`,'brief');$('#start').onclick=()=>travel('QUI EST VRAIMENT BON ?',game1)}

const profiles=[
{tag:'TRÈS IMPRESSIONNANT',name:'FlashMax',gain:'+44 %',note:'ça monte fort… puis ça casse',color:'#ff718d',path:'M2 58 C18 5,28 70,42 18 S65 82,79 14 S104 76,118 28 S140 68,158 18'},
{tag:'MOINS SPECTACULAIRE',name:'ZenVault',gain:'+18 %',note:'ça avance tranquillement',color:'#73ffd2',path:'M2 62 C22 58,28 53,44 55 S70 43,82 45 S105 34,120 36 S145 25,158 27'},
{tag:'COMPLÈTEMENT FOU',name:'YOLO_9000',gain:'+91 %',note:'impossible de savoir la suite',color:'#f6c76a',path:'M2 50 L18 12 L32 75 L48 5 L63 72 L79 18 L95 78 L112 8 L128 65 L143 22 L158 70'}];
function holo(p,i){return `<button class="holo" data-p="${i}" style="color:${p.color}" type="button"><span class="holo-shell"><i class="holo-avatar"></i><span class="mini-chart"><svg viewBox="0 0 160 84" preserveAspectRatio="none"><path d="${p.path}" stroke="${p.color}"/></svg></span><span class="holo-copy"><small>${p.tag}</small><h3>${p.name}</h3><b>${p.gain}</b><div style="margin-top:4px;color:#8897aa;font-size:11px">${p.note}</div></span><i class="holo-beam"></i></span></button>`}
function game1(){progress(1);render(`<div class="wrap level"><div class="level-top"><div><div class="level-index">EXPÉRIENCE 1</div><h2>Laquelle te paraît vraiment fiable ?</h2></div><div class="pill">TOUCHE UN PROFIL</div></div><p class="hint">Ne cherche pas le plus gros chiffre. Regarde surtout la forme de son parcours.</p><div class="stage holo-arena">${profiles.map(holo).join('')}</div><div id="g1answer"></div></div>`,'copy');$$('[data-p]').forEach(b=>b.onclick=()=>pickProfile(b))}
async function pickProfile(b){const i=Number(b.dataset.p),ok=i===1;$$('[data-p]').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');if(!ok)$$('[data-p]')[1].classList.add('correct');ok?sparkle():sfx('bad');if(!ok)toast('Le +91 % était spectaculaire… mais complètement imprévisible.');$('#g1answer').innerHTML=`<div class="reveal"><strong>${ok?'Exact.':'Le plus fiable était ZenVault.'}</strong> Ce qui intéresse Flo, ce n’est pas quelqu’un qui a gagné très fort une fois : c’est quelqu’un qui semble bien faire les choses <strong>encore et encore</strong>.${tech('COPY‑VAULT','Le logiciel observe beaucoup de portefeuilles pour repérer ceux dont le comportement semble réellement régulier.')}</div><div class="actions" style="margin-top:12px">${button('CONTINUER','to2')}</div>`;await say(ok?'Oui. Tu as choisi le moins spectaculaire… mais le plus rassurant.':'Piège du gros chiffre réussi. 😏 Le plus régulier était le meilleur choix.',2300);$('#to2').onclick=()=>travel('QUI BOUGE D’ABORD ?',game2)}

function game2(){progress(2);state.leadRound=0;state.leadWins=0;leadOpen=false;render(`<div class="wrap level"><div class="level-top"><div><div class="level-index">EXPÉRIENCE 2</div><h2>Regarde la ville de gauche.</h2></div><div class="pill">3 ESSAIS</div></div><p class="hint">Dès qu’elle s’allume, touche le bouton avant que l’énergie arrive à droite.</p><div class="stage city-stage"><div class="city-world a" id="cityA"><div class="city-towers"></div><div class="city-name"><small>ELLE BOUGE D’ABORD</small><b>VILLE A</b></div></div><div class="energy-line" id="track"><i class="energy"></i></div><div class="city-world b" id="cityB"><div class="city-towers"></div><div class="city-name"><small>ELLE SUIT APRÈS</small><b>VILLE B</b></div></div></div><div class="center"><button id="leadBtn" class="primary" type="button">LANCER L’ESSAI 1</button><div class="rounds" id="rounds" style="margin-top:12px"><i></i><i></i><i></i></div><div id="leadMsg" class="hint" style="margin:10px auto 0;text-align:center"></div></div></div>`,'lead');$('#leadBtn').onclick=startLead}
async function startLead(){if(leadOpen)return;const b=$('#leadBtn'),a=$('#cityA'),c=$('#cityB'),t=$('#track');b.disabled=true;$('#leadMsg').textContent='Regarde à gauche…';await sleep(700+Math.random()*600);a.classList.add('pulse');t.classList.remove('fly');void t.offsetWidth;t.classList.add('fly');sfx('soft');leadOpen=true;b.disabled=false;b.textContent='JE L’AI VU ! ⚡';b.onclick=()=>finishLead(true);leadTimer=setTimeout(()=>{if(!leadOpen)return;c.classList.add('target');finishLead(false)},1000)}
async function finishLead(win){if(!leadOpen)return;leadOpen=false;clearTimeout(leadTimer);const b=$('#leadBtn'),dots=$$('#rounds i');b.disabled=true;dots[state.leadRound].classList.add(win?'win':'miss');if(win){state.leadWins++;sparkle();$('#leadMsg').textContent='Oui : tu as réagi pendant que la deuxième ville était encore en retard.'}else{sfx('bad');$('#leadMsg').textContent='L’énergie était déjà arrivée à droite.'}state.leadRound++;await sleep(760);$('#cityA').classList.remove('pulse');$('#cityB').classList.remove('target');if(state.leadRound<3){b.disabled=false;b.textContent=`LANCER L’ESSAI ${state.leadRound+1}`;b.onclick=startLead}else{$('#leadMsg').innerHTML=`Tu viens simplement de voir qu’un mouvement peut arriver <strong>ici</strong>… puis un peu après <strong>là-bas</strong>.${tech('LEAD‑LAG','Le logiciel cherche les situations où un marché donne un indice juste avant qu’un autre ne réagisse complètement.')}`;b.disabled=false;b.textContent='CONTINUER';b.onclick=()=>travel('BONNE AFFAIRE OU PIÈGE ?',()=>game3(false))}}

function game3(good){progress(3);const left=100,right=good?102.60:101.80,gain=(right-left).toFixed(2);render(`<div class="wrap level"><div class="level-top"><div><div class="level-index">EXPÉRIENCE 3</div><h2>${good?'Encore une. Cette fois, regarde bien.':'Ça ressemble à de l’argent facile.'}</h2></div><div class="pill">MÊME OBJET · DEUX ENDROITS</div></div><p class="hint">Tu achètes le même objet moins cher à gauche et tu le revends plus cher à droite. On dirait un gain évident…</p><div class="stage market-stage"><div class="pedestal"><div><div class="shop-orb"><b>${left.toFixed(2)} €</b></div><div class="shop-name"><small>MAGASIN A</small><strong>ACHETER</strong></div></div></div><div class="trade-core"><div class="arrow">→</div><div>GAIN VISIBLE</div><div class="gain">+${gain} €</div><div id="costs" class="costs"></div><div id="net"></div></div><div class="pedestal right"><div><div class="shop-orb"><b>${right.toFixed(2)} €</b></div><div class="shop-name"><small>MAGASIN B</small><strong>REVENDRE</strong></div></div></div></div><div class="actions"><button id="checkDeal" class="primary" type="button">VÉRIFIER CE QU’IL RESTE</button></div><div id="g3answer"></div></div>`,'cross');$('#checkDeal').onclick=()=>checkDeal(good,gain)}
async function checkDeal(good,gross){const b=$('#checkDeal');b.disabled=true;const costs=good?[['Frais du passage',-.35],['Prix qui bouge',-.20],['Petit délai',-.15]]:[['Frais du passage',-.70],['Prix qui bouge',-.85],['Petit délai',-.55]];let net=Number(gross);for(const [name,val] of costs){await sleep(560);net+=val;$('#costs').insertAdjacentHTML('beforeend',`<div class="cost">${name} · ${val.toFixed(2)} €</div>`);sfx('hit')}await sleep(360);$('#net').innerHTML=`<div class="net ${net>0?'good':'bad'}">IL RESTE : ${net>=0?'+':''}${net.toFixed(2)} €</div>`;if(net<=0){sfx('bad');toast('Le joli gain a disparu.');$('#g3answer').innerHTML=`<div class="reveal"><strong>Voilà le piège.</strong> Le +${gross} € était vrai au départ, mais les petits coûts l’ont complètement mangé.</div><div class="actions" style="margin-top:12px">${button('MONTRE-MOI UNE VRAIE BONNE AFFAIRE','again')}</div>`;$('#again').onclick=()=>travel('UNE DEUXIÈME TENTATIVE',()=>game3(true))}else{sparkle();$('#g3answer').innerHTML=`<div class="reveal"><strong>Cette fois, il reste vraiment quelque chose.</strong> Flo ne s’arrête donc jamais au chiffre affiché au début : il regarde ce qu’il reste <strong>à la toute fin</strong>.${tech('CROSS‑VENUE','Le logiciel compare le même actif à plusieurs endroits, puis vérifie que l’écart survit réellement aux coûts.')}</div><div class="actions" style="margin-top:12px">${button('AFFRONTER LE BOSS','toBoss')}</div>`;$('#toBoss').onclick=()=>travel('BOSS · LE FAUX PROFIT',boss)}}

function boss(){progress(4);state.boss=25;state.bossHits=0;render(`<div class="wrap level"><div class="level-top"><div><div class="level-index">BOSS FINAL</div><h2>Ce +25 € dit qu’il est un vrai profit.</h2></div><div class="pill">VÉRIFIONS S’IL MENT</div></div><p class="hint">Appuie sur les quatre vérifications. C’est exactement ce que Flo fait à ses propres bonnes idées avant de leur faire confiance.</p><div class="stage boss-stage"><div class="boss-core" id="bossCore"><div class="boss-number"><b id="bossValue">+25 €</b><small>PROFIT QUI SE VANTE</small></div><div class="boss-health"><div class="boss-health-bar"><i id="bossBar"></i></div><small><span>CRÉDIBILITÉ</span><b id="bossPct">100 %</b></small></div></div></div><div class="attack-grid"><button class="attack" data-dmg="5" data-name="LES FRAIS">VÉRIFIER LES FRAIS</button><button class="attack" data-dmg="7" data-name="LE PRIX QUI BOUGE">VÉRIFIER LE PRIX PENDANT L’ACHAT</button><button class="attack" data-dmg="6" data-name="LE DÉLAI">VÉRIFIER LE DÉLAI</button><button class="attack" data-dmg="10" data-name="LE TEST RÉEL">VÉRIFIER SI ÇA MARCHE ENCORE</button></div><div id="bossMsg" class="center hint">Il a l’air beaucoup trop sûr de lui.</div></div>`,'boss');$$('.attack').forEach(b=>b.onclick=()=>hitBoss(b))}
async function hitBoss(b){if(b.classList.contains('done'))return;b.classList.add('done');state.boss-=Number(b.dataset.dmg);state.bossHits++;$('#bossValue').textContent=(state.boss>=0?'+':'')+state.boss+' €';const pct=Math.max(0,100-state.bossHits*25);$('#bossBar').style.width=pct+'%';$('#bossPct').textContent=pct+' %';$('#bossMsg').innerHTML=`<strong>${b.dataset.name}</strong> vient de retirer ${b.dataset.dmg} €.`;const core=$('#bossCore');core.classList.remove('boss-hit');void core.offsetWidth;core.classList.add('boss-hit');sfx('hit');haptic([12,28,12]);burst(innerWidth/2,innerHeight*.47,12);if(state.bossHits===4){await sleep(550);sparkle();$('#bossMsg').innerHTML=`Le magnifique <strong>+25 €</strong> est devenu <strong>−3 €</strong>. Il ne gagnait pas vraiment : il avait juste oublié tout ce qui l’arrangeait.`;$('#bossMsg').insertAdjacentHTML('afterend',`<div class="actions" style="margin-top:12px">${button('UNE DERNIÈRE DÉCISION','strategy')}</div>`);$('#strategy').onclick=()=>travel('LAQUELLE MÉRITE DE SURVIVRE ?',strategy)}}

function strategy(){render(`<div class="wrap level"><div class="level-top"><div><div class="level-index">APRÈS LE BOSS</div><h2>Laquelle te paraît vraiment digne de confiance ?</h2></div><div class="pill">NE TE LAISSE PAS ÉBLOUIR</div></div><p class="hint">Regarde surtout ce qui continue à marcher après beaucoup d’essais.</p><div class="stage crystal-stage"><button class="crystal" data-s="0"><i class="crystal-shape"></i><span class="crystal-copy"><small>TRÈS SPECTACULAIRE</small><b>+18 € affichés</b><p>Après les coûts : −3 €<br>51 essais · ça ne tient plus</p></span></button><button class="crystal" data-s="1"><i class="crystal-shape"></i><span class="crystal-copy"><small>PEUT-ÊTRE DE LA CHANCE</small><b>+12 €</b><p>Seulement 3 essais<br>On ne sait pas si ça tient</p></span></button><button class="crystal" data-s="2"><i class="crystal-shape"></i><span class="crystal-copy"><small>MOINS SEXY, MAIS SOLIDE</small><b>+4,20 €</b><p>42 essais<br>Ça marche encore ✓</p></span></button></div><div id="strategyMsg"></div></div>`,'boss');$$('[data-s]').forEach(b=>b.onclick=()=>pickStrategy(b))}
async function pickStrategy(b){const i=Number(b.dataset.s);if(i!==2){b.classList.add('wrong');sfx('bad');toast(i===0?'Le gros chiffre disparaît après les coûts.':'Trois essais, c’est beaucoup trop peu pour être rassuré.');return}$$('[data-s]').forEach(x=>x.disabled=true);b.classList.add('correct');sparkle();$('#strategyMsg').innerHTML=`<div class="reveal"><strong>Oui.</strong> Ce n’est pas le plus gros chiffre. C’est simplement celui qui continue à tenir quand on essaie vraiment de le casser.${tech('STRATÉGIE ROBUSTE','En gros : une idée qui ne fonctionne pas seulement par chance sur quelques données.')}</div><div class="actions" style="margin-top:12px">${button('TERMINER LA SESSION','toAline')}</div>`;await say('Et voilà pourquoi Flo préfère parfois un petit +4 solide à un énorme +25 imaginaire. 😏',2600);$('#toAline').onclick=()=>travel('ANALYSE DE FIN DE SESSION',aline)}

async function aline(){progress(4);render(`<div class="wrap aline-scene"><div class="level-index" style="color:#ff9fbe">ANOMALIE NON FINANCIÈRE DÉTECTÉE</div><div class="heart-orbit"><div class="heart">♥</div></div><h1>ALINE</h1><p id="alineText">Le laboratoire cherche encore pourquoi ce nom apparaît beaucoup trop souvent dans les données de Flo…</p><div id="alineAction"></div></div>`,'aline');const lines=['Présence dans les pensées : anormalement élevée.','Impact sur le propriétaire : impossible à chiffrer.','Tentative de suppression : refusée par Flo.','Conclusion : ce n’est probablement pas un bug. ❤️'];for(const l of lines){await sleep(850);$('#alineText').textContent=l;sfx('soft')}await sleep(650);$('#alineAction').innerHTML=button('VOIR TON RAPPORT FINAL','final') ;$('#final').onclick=finale}

function finale(){render(`<div class="wrap aline-scene"><div class="level-index" style="color:#ff9fbe">MISSION TERMINÉE</div><h1 style="font-size:clamp(46px,9vw,88px);letter-spacing:-.03em">Tu viens de comprendre son logiciel.</h1><p>Sans cours compliqué : chercher ce qui est régulier, repérer ce qui bouge avant le reste, et ne jamais croire un gros profit avant d’avoir vérifié ce qu’il reste vraiment.</p><div class="final-stats"><div class="stat"><small>LIGNES DE CODE</small><b>beaucoup trop</b></div><div class="stat"><small>TESTS</small><b>encore plus</b></div><div class="stat"><small>CAFÉS</small><b>données classifiées</b></div><div class="stat"><small>PENSÉES CONCERNANT ALINE</small><b>anomalie statistique confirmée ❤️</b></div></div><div class="signature">Merci d’être entrée quelques minutes dans mon petit monde. — Flo ❤️</div><div class="actions"><button id="replay" class="ghost" type="button">REJOUER</button></div></div>`,'aline');$('#replay').onclick=()=>{state.leadRound=0;state.leadWins=0;state.boss=25;state.bossHits=0;home()}}

home();
})();