(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const scene=$('#scene'),hud=$('#hud'),fill=$('#progressFill'),progressText=$('#progressText'),guideBox=$('#aiGuide'),guideText=$('#aiText'),toastBox=$('#toast'),flash=$('#flash'),soundButton=$('#soundButton');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const game={chapter:0,total:5,sound:true,leadRound:0,leadWins:0,bossValue:25,bossHits:0,finished:false};
let audioCtx=null,toastTimer=null;

function ensureAudio(){if(!game.sound)return null;try{const AC=window.AudioContext||window.webkitAudioContext;if(!audioCtx&&AC)audioCtx=new AC();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch(e){return null}}
function tone(freq=440,dur=.12,vol=.018,type='sine',delay=0){const ac=ensureAudio();if(!ac)return;try{const o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+dur+.03)}catch(e){}}
function sfx(kind){if(!game.sound)return;if(kind==='ok'){tone(520,.13,.014);tone(780,.18,.012,'sine',.08)}else if(kind==='bad'){tone(150,.18,.012,'triangle');tone(110,.23,.008,'sine',.05)}else if(kind==='pulse'){tone(260,.1,.01);tone(520,.12,.008,'sine',.06)}else if(kind==='boss'){tone(95,.28,.012,'sawtooth');tone(190,.18,.007,'triangle',.08)}else if(kind==='soft'){tone(330,.18,.009);tone(495,.28,.007,'sine',.1)}}
function vibrate(p){try{navigator.vibrate&&navigator.vibrate(p)}catch(e){}}
function sparkle(){flash.classList.remove('on');void flash.offsetWidth;flash.classList.add('on');sfx('ok');vibrate(18)}
function toast(msg){clearTimeout(toastTimer);toastBox.textContent=msg;toastBox.classList.add('on');toastTimer=setTimeout(()=>toastBox.classList.remove('on'),2400)}
function setProgress(n){game.chapter=n;fill.style.width=((n/game.total)*100)+'%';progressText.textContent=`${n} / ${game.total}`}
function render(html,cls=''){scene.className='scene';void scene.offsetWidth;scene.className='scene '+cls;scene.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'})}
async function guide(text,ms=2600){guideText.textContent=text;guideBox.classList.remove('hidden');sfx('soft');await sleep(ms);guideBox.classList.add('hidden')}
function nextButton(label,id='next'){return `<button id="${id}" class="primary" type="button">${label}</button>`}

soundButton.addEventListener('click',()=>{game.sound=!game.sound;soundButton.classList.toggle('muted',!game.sound);soundButton.textContent=game.sound?'SON':'MUET';if(game.sound){ensureAudio();sfx('ok')}});
document.addEventListener('pointerdown',e=>{if(e.target.closest('button'))vibrate(6)},{passive:true});

/* Fond vivant */
const canvas=$('#ambient'),ctx=canvas.getContext('2d');let W=0,H=0,D=1,particles=[];
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=W*D;canvas.height=H*D;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);particles=Array.from({length:Math.min(70,Math.max(34,Math.floor(W/14)))},()=>({x:Math.random()*W,y:Math.random()*H,r:.4+Math.random()*1.4,vx:(Math.random()-.5)*.12,vy:.08+Math.random()*.18,a:.12+Math.random()*.45,h:Math.random()>.5?188:286}))}
function ambient(){ctx.clearRect(0,0,W,H);const g=ctx.createRadialGradient(W*.5,H*.35,10,W*.5,H*.45,Math.max(W,H)*.75);g.addColorStop(0,'rgba(40,68,110,.18)');g.addColorStop(.45,'rgba(16,20,39,.08)');g.addColorStop(1,'rgba(4,6,12,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const p of particles){p.x+=p.vx;p.y-=p.vy;if(p.y<-8){p.y=H+8;p.x=Math.random()*W}if(p.x<-8)p.x=W+8;if(p.x>W+8)p.x=-8;ctx.beginPath();ctx.fillStyle=`hsla(${p.h},90%,75%,${p.a})`;ctx.shadowColor=`hsla(${p.h},90%,70%,.5)`;ctx.shadowBlur=8;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;requestAnimationFrame(ambient)}
addEventListener('resize',resize);resize();requestAnimationFrame(ambient);

function intro(){hud.classList.add('hidden');setProgress(0);render(`<div class="wrap intro">
  <div class="eyebrow">EXPÉRIENCE PRIVÉE · SUJET AUTORISÉ : ALINE</div>
  <div class="hero-mark"><div class="hero-core"><span>A</span></div></div>
  <h1><span class="gradient-text">Entre dans le cerveau du bot.</span></h1>
  <p class="lead">Flo travaille sur un logiciel assez compliqué. T’expliquer ça avec 47 graphiques aurait été cruel. Alors aujourd’hui, tu vas simplement <strong>entrer dedans.</strong></p>
  ${nextButton('ENTRER DANS LE LABORATOIRE','enterLab')}
  <div class="micro">Aucune connaissance en trading requise. Un minimum de courage peut aider.</div>
</div>`,'intro-scene');
$('#enterLab').onclick=async()=>{ensureAudio();sfx('pulse');sparkle();hud.classList.remove('hidden');renderLabBrief();await guide('Bienvenue Aline. Je suis l’IA du laboratoire. Mon rôle : traduire les trucs compliqués de Flo en quelque chose d’humain.',3600)} }

function renderLabBrief(){render(`<div class="wrap level"><div class="mission-head"><div><div class="mission-kicker">BRIEFING</div><h2>Ta mission : comprendre sans t’ennuyer.</h2></div><div class="mission-pill">DURÉE : quelques minutes</div></div><p class="brief">Tu vas traverser trois moteurs du logiciel. Dans chaque salle, une petite expérience te fera comprendre l’idée avant l’explication. À la fin, un boss vérifiera si tu as vraiment compris pourquoi Flo passe autant de temps à tester ses stratégies.</p><div class="panel panel-glow"><div class="statusline"><i></i> PARCOURS CHARGÉ</div><div class="lesson-grid" style="margin-top:14px"><div class="lesson"><div class="num">01</div><h3>Copy‑Vault</h3><p>Repérer les traders réellement solides.</p></div><div class="lesson"><div class="num">02</div><h3>Lead‑Lag</h3><p>Comprendre qui bouge avant qui.</p></div><div class="lesson"><div class="num">03</div><h3>Cross‑Venue</h3><p>Savoir si un écart vaut vraiment de l’argent.</p></div></div></div><div class="button-row">${nextButton('LANCER LA MISSION','startMission')}</div></div>`);$('#startMission').onclick=()=>copyVault()}

const traders=[
{name:'FlashMax',tag:'LE SPECTACULAIRE',pnl:'+44 %',regular:'très faible',risk:'high',path:'M2 58 C18 5,28 70,42 18 S65 82,79 14 S104 76,118 28 S140 68,158 18',stroke:'#ff718d'},
{name:'ZenVault',tag:'LE RÉGULIER',pnl:'+18 %',regular:'élevée',risk:'low',path:'M2 62 C22 58,28 53,44 55 S70 43,82 45 S105 34,120 36 S145 25,158 27',stroke:'#73ffd2'},
{name:'YOLO_9000',tag:'LE CHAOS',pnl:'+91 %',regular:'inconnue',risk:'high',path:'M2 50 L18 12 L32 75 L48 5 L63 72 L79 18 L95 78 L112 8 L128 65 L143 22 L158 70',stroke:'#f6c76a'}
];
function traderCard(t,i){return `<button class="trader" data-trader="${i}" type="button"><small>${t.tag}</small><h3>${t.name}</h3><div class="metric"><span>Performance</span><b>${t.pnl}</b></div><div class="metric"><span>Régularité</span><b>${t.regular}</b></div><div class="sparkline"><svg viewBox="0 0 160 84" preserveAspectRatio="none"><path d="${t.path}" stroke="${t.stroke}"/></svg></div><div class="risk"><span class="risk-${t.risk}"></span></div></button>`}
function copyVault(){setProgress(1);render(`<div class="wrap level"><div class="mission-head"><div><div class="mission-kicker">NIVEAU 1 · COPY‑VAULT</div><h2>Qui mérite vraiment d’être suivi ?</h2></div><div class="mission-pill">OBJECTIF : ROBUSTESSE</div></div><p class="brief">Trois traders apparaissent dans le radar. Ne choisis pas forcément celui qui affiche le plus gros chiffre. Cherche celui dont le comportement paraît le plus exploitable sur la durée.</p><div class="trader-grid">${traders.map(traderCard).join('')}</div><div id="copyExplain"></div></div>`);$$('[data-trader]').forEach(b=>b.onclick=()=>chooseTrader(Number(b.dataset.trader)))}
async function chooseTrader(i){$$('[data-trader]').forEach(b=>b.disabled=true);const cards=$$('[data-trader]'),ok=i===1;cards[i].classList.add(ok?'correct':'wrong');cards[1].classList.add('selected');ok?sparkle():sfx('bad');if(!ok)toast('Piège : le plus gros + n’est pas forcément le meilleur.');$('#copyExplain').innerHTML=`<div class="explain"><strong>${ok?'Exact.':'Le meilleur choix était ZenVault.'}</strong> Copy‑Vault ne cherche pas juste quelqu’un qui a eu un énorme coup de chance. Le logiciel observe beaucoup de portefeuilles et cherche surtout des comportements <strong>réguliers, reproductibles et robustes.</strong></div><div class="button-row" style="margin-top:14px">${nextButton('PASSER AU LEAD‑LAG','toLead')}</div>`;await guide(ok?'Bien vu. Un +91 % peut être magnifique… et complètement inutilisable. Flo essaie de distinguer le talent du coup de chance.':'Tu es tombée dans le piège classique. Rassure-toi : énormément de stratégies aussi.',3000);$('#toLead').onclick=()=>leadLag()}

function leadLag(){setProgress(2);game.leadRound=0;game.leadWins=0;render(`<div class="wrap level"><div class="mission-head"><div><div class="mission-kicker">NIVEAU 2 · LEAD‑LAG</div><h2>Un marché bouge. L’autre n’a pas encore compris.</h2></div><div class="mission-pill">3 MANCHES</div></div><p class="brief">Quand le marché A reçoit un choc, le marché B réagit parfois quelques instants plus tard. Dès que A s’allume, touche ANTICIPER avant que le signal n’atteigne B.</p><div class="panel lead-arena"><div id="marketA" class="market-node"><div><small>MARCHÉ A · LEADER</small><strong>ALPHA</strong></div><span class="pulse"></span></div><div id="linkTrack" class="link-track"></div><div id="marketB" class="market-node"><div><small>MARCHÉ B · RETARDATAIRE</small><strong>BETA</strong></div><span class="pulse"></span></div></div><div class="reaction-zone"><button id="leadAction" class="primary" type="button">LANCER LA MANCHE 1</button><div id="rounds" class="rounds">${[0,1,2].map(()=>'<span class="round-dot"></span>').join('')}</div><div id="leadMsg" class="boss-log"></div></div></div>`);$('#leadAction').onclick=startLeadRound}
let leadTimer=null,leadOpen=false;
async function startLeadRound(){if(leadOpen)return;const btn=$('#leadAction'),a=$('#marketA'),b=$('#marketB'),track=$('#linkTrack'),msg=$('#leadMsg');btn.disabled=true;msg.textContent='Écoute le marché…';await sleep(650+Math.random()*600);a.classList.remove('hit');void a.offsetWidth;a.classList.add('hit');track.classList.remove('fly');void track.offsetWidth;track.classList.add('fly');sfx('pulse');leadOpen=true;btn.disabled=false;btn.textContent='ANTICIPER B ⚡';btn.onclick=()=>finishLeadRound(true);const travel=950;leadTimer=setTimeout(()=>{if(!leadOpen)return;b.classList.add('target-hit');finishLeadRound(false)},travel)}
async function finishLeadRound(win){if(!leadOpen)return;leadOpen=false;clearTimeout(leadTimer);const btn=$('#leadAction'),msg=$('#leadMsg'),dots=$$('.round-dot');btn.disabled=true;if(win){game.leadWins++;dots[game.leadRound].classList.add('win');msg.textContent='Bien joué : tu as agi pendant que B était encore en retard.';sparkle()}else{dots[game.leadRound].classList.add('miss');msg.textContent='Trop tard : le signal avait déjà atteint B.';sfx('bad')}game.leadRound++;await sleep(950);$('#marketB').classList.remove('target-hit');if(game.leadRound<3){btn.disabled=false;btn.textContent=`LANCER LA MANCHE ${game.leadRound+1}`;btn.onclick=startLeadRound}else{msg.innerHTML=`Score : <strong>${game.leadWins}/3</strong>. Le principe important n’est pas ta vitesse : c’est que certains marchés <strong>transmettent l’information avant d’autres.</strong>`;btn.disabled=false;btn.textContent='CONTINUER';btn.onclick=async()=>{await guide('Voilà le Lead‑Lag : le bot cherche des relations où un marché donne un indice avant qu’un autre ait complètement réagi.',3200);crossVenue()}}}

function crossVenue(){setProgress(3);renderCrossScenario(false)}
function renderCrossScenario(good){const left=good?100.00:100.00,right=good?100.48:100.18,gross=(right-left).toFixed(2);render(`<div class="wrap level"><div class="mission-head"><div><div class="mission-kicker">NIVEAU 3 · CROSS‑VENUE</div><h2>${good?'Deuxième tentative.':'Ça ressemble à de l’argent gratuit…'}</h2></div><div class="mission-pill">PROFIT BRUT : +${gross} $</div></div><p class="brief">Même actif, deux plateformes. Tu achètes là où c’est moins cher et tu vends là où c’est plus cher. Facile ? Clique, puis laisse le logiciel faire les calculs que l’œil oublie.</p><div class="venue-grid"><div class="venue"><div class="logo">PLATEFORME A</div><div class="price">${left.toFixed(2)} $</div><small>Prix d’achat</small></div><div class="venue"><div class="logo">PLATEFORME B</div><div class="price">${right.toFixed(2)} $</div><small>Prix de vente</small></div></div><div id="moneyFlow" class="money-flow"><div class="money-row"><span>Écart brut</span><b>+${gross} $</b></div></div><div class="button-row" style="margin-top:16px"><button id="takeTrade" class="primary" type="button">JE PRENDS L’OPPORTUNITÉ</button></div></div>`);$('#takeTrade').onclick=()=>revealCosts(good)}
async function revealCosts(good){const btn=$('#takeTrade'),flow=$('#moneyFlow');btn.disabled=true;const costs=good?[['Frais',-.08],['Spread',-.05],['Slippage',-.04],['Latence',-.05]]:[['Frais',-.08],['Spread',-.05],['Slippage',-.04],['Latence',-.06]];let net=good?.48:.18;for(const [name,val] of costs){await sleep(700);net+=val;flow.insertAdjacentHTML('beforeend',`<div class="money-row cost"><span>${name}</span><b>${val.toFixed(2)} $</b></div>`);sfx('boss')}await sleep(500);flow.insertAdjacentHTML('beforeend',`<div class="money-row net ${net>0?'good':'bad'}"><span>PROFIT NET</span><b>${net>=0?'+':''}${net.toFixed(2)} $</b></div>`);if(net>0){sparkle();flow.insertAdjacentHTML('afterend',`<div class="explain"><strong>Cette fois, l’écart survit.</strong> Le bot ne s’intéresse pas seulement au prix affiché : il estime ce qui resterait réellement après les coûts et la latence.</div><div class="button-row" style="margin-top:14px">${nextButton('ACCÉDER AU TEST FINAL','toBoss')}</div>`);$('#toBoss').onclick=async()=>{await guide('Tu viens de comprendre le Cross‑Venue : un joli écart brut ne vaut rien si les coûts le mangent avant l’exécution.',3000);boss()}}else{sfx('bad');toast('Le profit a disparu. Bienvenue dans la vraie vie.');flow.insertAdjacentHTML('afterend',`<div class="explain"><strong>Piège.</strong> Sur l’écran, +0,18 $ semblait gagné. Après frais, spread, slippage et latence : <strong>${net.toFixed(2)} $</strong>. C’est exactement le genre de faux signal que le logiciel doit éliminer.</div><div class="button-row" style="margin-top:14px">${nextButton('VOIR UNE VRAIE OPPORTUNITÉ','crossAgain')}</div>`);$('#crossAgain').onclick=()=>renderCrossScenario(true)}}

function boss(){setProgress(4);game.bossValue=25;game.bossHits=0;render(`<div class="wrap level boss-wrap" id="bossRoot"><div class="boss-title">TEST FINAL · BOSS</div><h2 style="font-size:clamp(38px,9vw,72px);margin:8px 0">LE FAUX PROFIT</h2><p class="brief" style="margin-inline:auto">Une stratégie annonce fièrement +25 $. Ton travail : lancer les audits que les belles captures d’écran préfèrent oublier.</p><div class="profit-orb"><div><div id="profitValue" class="profit-value">+25 $</div><div class="profit-label">PROFIT APPARENT</div></div></div><div class="enemy-row"><button class="attack-button" data-cost="5" data-label="FRAIS">AUDITER FRAIS</button><button class="attack-button" data-cost="7" data-label="SLIPPAGE">AUDITER SLIPPAGE</button><button class="attack-button" data-cost="6" data-label="LATENCE">AUDITER LATENCE</button><button class="attack-button" data-cost="10" data-label="MAUVAIS SIGNAL">TESTER LE SIGNAL</button></div><div id="bossLog" class="boss-log">Le boss a l’air très confiant. C’est suspect.</div></div>`);$$('.attack-button').forEach(b=>b.onclick=()=>hitBoss(b))}
async function hitBoss(btn){if(btn.classList.contains('defeated'))return;btn.classList.add('defeated');const cost=Number(btn.dataset.cost);game.bossValue-=cost;game.bossHits++;$('#profitValue').textContent=(game.bossValue>=0?'+':'')+game.bossValue+' $';$('#bossLog').innerHTML=`<strong>${btn.dataset.label}</strong> vient de retirer ${cost} $.`;sfx('boss');vibrate([12,25,12]);if(game.bossHits===4){await sleep(650);$('#bossRoot').classList.add('boss-dead');$('#bossLog').innerHTML=`Le magnifique <strong>+25 $</strong> est devenu <strong>−3 $</strong>. Boss démasqué : ce n’était pas un profit, juste un résultat mal testé.`;await sleep(1700);renderStrategyChoice()}}
function renderStrategyChoice(){render(`<div class="wrap level"><div class="mission-head"><div><div class="mission-kicker">BOSS · PHASE 2</div><h2>Laquelle mérite de survivre ?</h2></div><div class="mission-pill">DERNIER FILTRE</div></div><p class="brief">Trois stratégies ont passé le laboratoire. Regarde surtout le résultat net, le nombre d’essais et si ça tient encore hors de l’échantillon utilisé pour la construire.</p><div class="trader-grid"><button class="trader strategy" data-strategy="0"><small>ROCKET MODE</small><h3>+18 $ brut</h3><div class="metric"><span>Net</span><b>−3 $</b></div><div class="metric"><span>Échantillon</span><b>51 trades</b></div><div class="metric"><span>Hors échantillon</span><b>négatif</b></div></button><button class="trader strategy" data-strategy="1"><small>LUCKY SHOT</small><h3>+12 $ net</h3><div class="metric"><span>Net</span><b>+12 $</b></div><div class="metric"><span>Échantillon</span><b>3 trades</b></div><div class="metric"><span>Hors échantillon</span><b>?</b></div></button><button class="trader strategy" data-strategy="2"><small>ROBUSTE</small><h3>+4,20 $ net</h3><div class="metric"><span>Net</span><b>positif</b></div><div class="metric"><span>Échantillon</span><b>42 trades</b></div><div class="metric"><span>Hors échantillon</span><b>positif</b></div></button></div><div id="strategyExplain"></div></div>`);$$('[data-strategy]').forEach(b=>b.onclick=()=>chooseStrategy(b))}
async function chooseStrategy(b){const i=Number(b.dataset.strategy);if(i!==2){b.classList.add('wrong');sfx('bad');toast(i===1?'+12 $ sur 3 essais ? Flo aurait déjà ouvert le champagne trop tôt.':'Un résultat brut positif avec un net négatif : prison immédiate.');return}$$('[data-strategy]').forEach(x=>x.disabled=true);b.classList.add('correct');sparkle();$('#strategyExplain').innerHTML=`<div class="explain"><strong>Victoire.</strong> Le chiffre est moins spectaculaire, mais il survit aux coûts, possède assez d’observations et reste positif hors échantillon. C’est précisément ce que le logiciel cherche : <strong>quelque chose qui résiste aux tests.</strong></div><div class="button-row" style="margin-top:14px">${nextButton('TERMINER LA MISSION','finishBoss')}</div>`;$('#finishBoss').onclick=async()=>{await guide('Mission accomplie. Tu sais maintenant pourquoi Flo préfère parfois un petit +4 solide à un énorme +25 imaginaire.',3400);anomaly()}}

async function anomaly(){setProgress(5);render(`<div class="wrap anomaly"><div class="anomaly-code" id="anomalyCode">ANALYSE DE FIN DE SESSION…</div><div class="heartline">♡</div><h2>ALINE</h2><p class="lead" style="max-width:640px;margin-inline:auto">Variable inattendue détectée dans le laboratoire.</p><div id="anomalyStats" class="anomaly-stats" style="opacity:0"><div class="anomaly-stat"><small>PRÉSENCE DANS LES PENSÉES</small><b>ANORMALEMENT ÉLEVÉE</b></div><div class="anomaly-stat"><small>IMPACT SUR LE PROPRIÉTAIRE</small><b>+∞</b></div><div class="anomaly-stat"><small>CORRECTIF DISPONIBLE</small><b>AUCUN ❤️</b></div></div><div id="anomalyAction"></div></div>`,'anomaly-scene');const code=$('#anomalyCode');const lines=['ANALYSE DE FIN DE SESSION…','VARIABLE INCONNUE : ALINE','RECHERCHE D’UNE ERREUR…','ERREUR INTROUVABLE.','CONCLUSION : LE PROPRIÉTAIRE REFUSE TOUT CORRECTIF.'];for(const l of lines){code.textContent=l;sfx('pulse');await sleep(850)}$('#anomalyStats').style.opacity='1';sparkle();await guide('Euh… Aline ? J’ai trouvé un bug que Flo refuse catégoriquement de corriger. Apparemment, il s’appelle toi.',3800);$('#anomalyAction').innerHTML=nextButton('VOIR LE RAPPORT FINAL','finalReport');$('#finalReport').onclick=finale}

function finale(){game.finished=true;render(`<div class="wrap final"><div class="final-badge">✓ MISSION TERMINÉE</div><h1><span class="gradient-text">Bienvenue dans le monde de Flo.</span></h1><p class="lead">Tu sais maintenant, sans avoir subi un cours de 2 heures, ce que le logiciel essaie de faire : trouver les comportements solides, détecter qui réagit avant qui, et refuser les profits qui disparaissent dès qu’on calcule correctement.</p><div class="lesson-grid"><div class="lesson"><div class="num">COPY‑VAULT</div><h3>Observer les meilleurs.</h3><p>Mais surtout distinguer la régularité du simple coup de chance.</p></div><div class="lesson"><div class="num">LEAD‑LAG</div><h3>Voir le mouvement arriver.</h3><p>Repérer quand un marché transmet une information avant un autre.</p></div><div class="lesson"><div class="num">CROSS‑VENUE</div><h3>Compter ce qui reste.</h3><p>Un écart n’est intéressant que s’il survit aux coûts réels.</p></div></div><div class="absurd"><div><small>LIGNES DE CODE</small><b>beaucoup trop</b></div><div><small>TESTS EFFECTUÉS</small><b>encore plus</b></div><div><small>CAFÉS CONSOMMÉS</small><b>données classifiées</b></div><div><small>PENSÉES CONCERNANT ALINE</small><b>anomalie statistique détectée ❤️</b></div></div><div class="last-note">Merci d’avoir visité mon petit monde. Maintenant, quand je parlerai de Lead‑Lag ou de slippage, tu pourras au minimum faire semblant de comprendre avec beaucoup plus de crédibilité. 😏❤️<div class="signature">— Flo</div></div><div class="button-row" style="margin-top:18px"><button id="replay" class="secondary" type="button">REJOUER L’EXPÉRIENCE</button></div></div>`,'final-scene');sparkle();guideBox.classList.add('hidden');$('#replay').onclick=()=>{game.leadRound=0;game.leadWins=0;game.bossValue=25;game.bossHits=0;game.finished=false;intro()}}

intro();
})();