(()=>{'use strict';
const scene=document.querySelector('#scene');if(!scene)return;
const reduced=window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches;
const coarse=window.matchMedia&&matchMedia('(pointer: coarse)').matches;
const body=document.body,html=document.documentElement;
const fx=document.createElement('canvas');fx.id='v3fx';fx.setAttribute('aria-hidden','true');body.insertBefore(fx,body.firstChild.nextSibling);
const vignette=document.createElement('div');vignette.className='v3-vignette';vignette.setAttribute('aria-hidden','true');body.appendChild(vignette);
const beam=document.createElement('div');beam.className='v3-lightbeam';beam.setAttribute('aria-hidden','true');body.appendChild(beam);
const sceneLabel=document.createElement('div');sceneLabel.className='v3-scene-label';sceneLabel.setAttribute('aria-hidden','true');body.appendChild(sceneLabel);
const ctx=fx.getContext('2d',{alpha:true});let W=0,H=0,D=1,points=[],tier='',pointer={x:0,y:0,active:false},last=performance.now();
const palettes={default:[[103,235,255],[133,112,255],[255,126,185]],copy:[[91,246,207],[83,216,255],[142,137,255]],lead:[[105,232,255],[111,121,255],[255,118,187]],cross:[[255,224,119],[100,229,255],[255,119,164]],boss:[[255,90,128],[255,174,74],[190,105,255]],aline:[[255,155,190],[255,215,229],[214,157,255]],final:[[255,215,229],[255,157,190],[240,199,116]]};
function world(){if(body.classList.contains('world-copy'))return'copy';if(body.classList.contains('world-lead'))return'lead';if(body.classList.contains('world-cross'))return'cross';if(body.classList.contains('world-boss'))return'boss';if(body.classList.contains('world-aline')||body.classList.contains('aline-shift'))return'aline';if(body.classList.contains('world-final'))return'final';return'default'}
function desiredCount(){if(reduced)return 0;if(html.classList.contains('quality-low'))return 28;if(html.classList.contains('quality-max'))return Math.min(92,Math.max(60,Math.floor(W/8)));return Math.min(68,Math.max(40,Math.floor(W/11)))}
function makePoint(){return{x:Math.random()*W,y:Math.random()*H,px:0,py:0,z:.25+Math.random()*.75,r:.45+Math.random()*1.55,s:.05+Math.random()*.19,a:.08+Math.random()*.34,phase:Math.random()*Math.PI*2,c:Math.floor(Math.random()*3)}}
function resize(){W=innerWidth;H=innerHeight;const cap=html.classList.contains('quality-low')?1:1.55;D=Math.min(devicePixelRatio||1,cap);fx.width=Math.max(1,Math.floor(W*D));fx.height=Math.max(1,Math.floor(H*D));fx.style.width=W+'px';fx.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);tier='';syncCount()}
function syncCount(){const key=(html.classList.contains('quality-low')?'low':html.classList.contains('quality-max')?'max':'auto')+':'+desiredCount();if(key===tier)return;tier=key;const n=desiredCount();if(points.length<n){while(points.length<n)points.push(makePoint())}else if(points.length>n)points.length=n}
function rgba(c,a){return`rgba(${c[0]},${c[1]},${c[2]},${a})`}
function drawMotes(t,dt,pal){ctx.save();ctx.globalCompositeOperation='lighter';for(const p of points){p.px=p.x;p.py=p.y;p.y-=p.s*(.55+p.z)*dt*.06;p.x+=Math.sin(t*.00035+p.phase)*p.s*dt*.018;if(pointer.active){const dx=pointer.x-p.x,dy=pointer.y-p.y,d=Math.hypot(dx,dy)||1;if(d<180){p.x-=dx/d*(180-d)*.0009*dt;p.y-=dy/d*(180-d)*.0009*dt}}if(p.y<-12){p.y=H+12;p.x=Math.random()*W}if(p.x<-15)p.x=W+15;if(p.x>W+15)p.x=-15;const c=pal[p.c%pal.length],pulse=.72+.28*Math.sin(t*.0012+p.phase);ctx.strokeStyle=rgba(c,p.a*.15);ctx.lineWidth=.6*p.z;ctx.beginPath();ctx.moveTo(p.px,p.py);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle=rgba(c,p.a*pulse);ctx.shadowColor=rgba(c,.45);ctx.shadowBlur=8*p.z;ctx.beginPath();ctx.arc(p.x,p.y,p.r*p.z,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.shadowBlur=0}
function drawCopy(t,pal){const cx=W*.5,cy=H*.42,r=Math.min(W,H)*.22;ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<8;i++){const a=t*.00008+i*Math.PI/4,x=cx+Math.cos(a)*r*(.78+(i%3)*.08),y=cy+Math.sin(a)*r*.45;ctx.fillStyle=rgba(pal[i%3],.16);ctx.beginPath();ctx.arc(x,y,2.2+(i%2),0,Math.PI*2);ctx.fill();ctx.strokeStyle=rgba(pal[i%3],.06);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(x,y);ctx.stroke()}ctx.restore()}
function drawLead(t,pal){const y=H*.52,x1=W*.13,x2=W*.87;ctx.save();ctx.globalCompositeOperation='lighter';const g=ctx.createLinearGradient(x1,y,x2,y);g.addColorStop(0,rgba(pal[0],.02));g.addColorStop(.5,rgba(pal[1],.12));g.addColorStop(1,rgba(pal[2],.02));ctx.strokeStyle=g;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(x1,y);ctx.lineTo(x2,y);ctx.stroke();for(let i=0;i<3;i++){const q=((t*.00018+i*.29)%1),x=x1+(x2-x1)*q;ctx.fillStyle=rgba(pal[i%3],.18*(1-Math.abs(q-.5)*.8));ctx.shadowColor=rgba(pal[i%3],.45);ctx.shadowBlur=18;ctx.beginPath();ctx.arc(x,y,2.5+i*.7,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.shadowBlur=0}
function drawCross(t,pal){ctx.save();ctx.globalCompositeOperation='lighter';for(let side=0;side<2;side++){const base=side?W*.78:W*.22;for(let i=0;i<6;i++){const y=H*(.24+i*.09)+Math.sin(t*.001+i+side)*6;const w=28+Math.sin(t*.0008+i)*12;ctx.strokeStyle=rgba(pal[(i+side)%3],.055+.025*(i%2));ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(base-w,y);ctx.lineTo(base+w,y);ctx.stroke()}}ctx.restore()}
function drawBoss(t,pal){const cx=W*.5,cy=H*.47,r=Math.min(W,H)*.20;ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<3;i++){ctx.strokeStyle=rgba(pal[i],.07+i*.015);ctx.lineWidth=1+i*.35;ctx.beginPath();ctx.arc(cx,cy,r+i*18,t*.00035*(i%2?1:-1)+i,t*.00035*(i%2?1:-1)+i+Math.PI*1.2);ctx.stroke()}ctx.restore()}
function drawHeart(t,pal){const cx=W*.5,cy=H*.44,scale=Math.min(W,H)*.0125*(1+.025*Math.sin(t*.002));ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<42;i++){const a=(i/42)*Math.PI*2,x=16*Math.pow(Math.sin(a),3),y=-(13*Math.cos(a)-5*Math.cos(2*a)-2*Math.cos(3*a)-Math.cos(4*a));const px=cx+x*scale,py=cy+y*scale;ctx.fillStyle=rgba(pal[i%3],.08+.05*Math.sin(t*.001+i));ctx.beginPath();ctx.arc(px,py,1.2+(i%4)*.25,0,Math.PI*2);ctx.fill()}ctx.restore()}
function frame(now){const dt=Math.min(40,now-last||16);last=now;syncCount();ctx.clearRect(0,0,W,H);const w=world(),pal=palettes[w]||palettes.default;drawMotes(now,dt,pal);if(!reduced&&!html.classList.contains('quality-low')){if(w==='copy')drawCopy(now,pal);else if(w==='lead')drawLead(now,pal);else if(w==='cross')drawCross(now,pal);else if(w==='boss')drawBoss(now,pal);else if(w==='aline'||w==='final')drawHeart(now,pal)}requestAnimationFrame(frame)}
addEventListener('resize',resize,{passive:true});addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;pointer.active=true},{passive:true});addEventListener('pointerleave',()=>pointer.active=false,{passive:true});resize();requestAnimationFrame(frame);
function syncWorld(){const classes=['world-copy','world-lead','world-cross','world-boss','world-aline','world-final'];let cls='',label='LABORATOIRE HYPERSMART';if(scene.querySelector('[data-trader]')){cls='world-copy';label='CHAMBRE D’OBSERVATION'}else if(scene.querySelector('#marketA')){cls='world-lead';label='COULOIR DE PROPAGATION'}else if(scene.querySelector('.venue-grid')){cls='world-cross';label='ARÈNE DES PRIX'}else if(scene.querySelector('#bossRoot')||scene.querySelector('[data-strategy]')){cls='world-boss';label='ZONE DE TEST EXTRÊME'}else if(scene.querySelector('.anomaly')){cls='world-aline';label='ANOMALIE NON FINANCIÈRE'}else if(scene.querySelector('.final')){cls='world-final';label='MISSION TERMINÉE'}classes.forEach(c=>{if(c!==cls)body.classList.remove(c)});if(cls)body.classList.add(cls);sceneLabel.textContent=label}
let worldQueued=false;const queueWorld=()=>{if(worldQueued)return;worldQueued=true;requestAnimationFrame(()=>{worldQueued=false;syncWorld();decorateSuccess()})};new MutationObserver(queueWorld).observe(scene,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});syncWorld();
const portalNames={enterLab:'ENTRÉE DANS LE LABORATOIRE',startMission:'JEU 1 · TROUVE LE VRAI BON',toLead:'JEU 2 · QUI BOUGE D’ABORD ?',crossAgain:'UNE VRAIE BONNE AFFAIRE',toBoss:'LE BOSS DU FAUX PROFIT',finishBoss:'DERNIÈRE ANALYSE',finalReport:'TON RAPPORT FINAL'};document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('button');if(!b)return;const name=portalNames[b.id];if(name){const n=document.querySelector('#portalName');if(n)n.textContent=name}const ring=document.createElement('i');ring.className='v3-tap';ring.style.left=e.clientX+'px';ring.style.top=e.clientY+'px';body.appendChild(ring);setTimeout(()=>ring.remove(),700)},true);
function decorateSuccess(){scene.querySelectorAll('.correct:not([data-v3-bloom]),.concept-reveal:not([data-v3-bloom])').forEach(el=>{el.dataset.v3Bloom='1';if(reduced)return;const r=el.getBoundingClientRect(),b=document.createElement('div');b.className='v3-success-bloom';b.style.setProperty('--x',(r.left+r.width/2)+'px');b.style.setProperty('--y',(r.top+r.height/2)+'px');body.appendChild(b);setTimeout(()=>b.remove(),760)})}
if(!coarse&&!reduced){let active=null,raf=0;document.addEventListener('pointermove',e=>{const el=e.target.closest&&e.target.closest('.trader,.venue,.lesson,.panel');if(!el){if(active){active.style.transform='';active=null}return}active=el;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateX(${-y*3.5}deg) rotateY(${x*4.5}deg) translateY(-2px)`})},{passive:true});document.addEventListener('pointerout',e=>{const el=e.target.closest&&e.target.closest('.trader,.venue,.lesson,.panel');if(el&&!el.contains(e.relatedTarget)){el.style.transform='';if(active===el)active=null}},{passive:true})}
})();